apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kube-system
  namespace: argo-cd
spec:
  destinations:
    - name: in-cluster
      namespace: kube-system
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - https://github.com/Blarc/home-k8s
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argo-cd
spec:
  project: kube-system
  source:
    repoURL: https://github.com/Blarc/home-k8s
    targetRevision: main
    path: 'kubernetes/wireguard'
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

