app-template:
  controllers:
    pdf-scrawl:
      containers:
        app:
          env:
            COOKIE_NAME: ENC[AES256_GCM,data:Lv7twyF+fA==,iv:QA7i2oTtEIDPYKd5AD/LEMgAnP882Ag7jG+Ae02BAMQ=,tag:PHxFTkVZ8LoMjkLHPFnr2w==,type:str]
            COOKIE_SALT: ENC[AES256_GCM,data:nVKohoPcLN7mz31rr40bLQ==,iv:mqvRBQ/jK8swUJ2N2UT4qLUrrAOYmhQIS9VCFeWwnQk=,tag:nEajFpbhFDFybMf92Dp4Ew==,type:str]
            COOKIE_SECRET: ENC[AES256_GCM,data:d7Vybz28J4OPUynI+X09Nxky6HSixNTKb/IvGCN1K4Q=,iv:NhFKPXAYhoFRWJOA+avHFgf+2S7VP+Z648gHqwSdI30=,tag:bSEYBUfpAdQwDMPHAEP+HQ==,type:str]
            NODE_ENV: ENC[AES256_GCM,data:nvZs5GTGyiNJ7Q==,iv:j4ItkbztzjZ18RnHIuXW/WRvFXOeSJQnioramQFwSb8=,tag:/EJGNYXc+qx06tZJsOWX1A==,type:str]
            HOST: ENC[AES256_GCM,data:a3WXm3b9nQ==,iv:r2qBAVg+eyxJ+GGXrcRm/611bgrUAZvuPdgFhsXCJwQ=,tag:Q0L1hwu9LuIYUNMk6ZDyLg==,type:str]
            PORT: ENC[AES256_GCM,data:3makwA==,iv:jb2QsDkfLkneENnU0ykwyb1tj4Zvyix06Y7tbSF83Dg=,tag:9oPMcRg+4YDieCKGD5G1CA==,type:int]
            PDF_DIR: ENC[AES256_GCM,data:6ui43g==,iv:D+jsCJuXf6m/Lpi/56a8u8L4ePQPEjXEHQvdfbeb7HE=,tag:4PZ51VNLHbGsWtmImdqvqg==,type:str]
sops:
  age:
    - recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYmMrcG1JaUJpTEhhYzBM
        Q2ZXWjZ1RHpZeXlBS0ZUcjlEeGFMejJveUQ0ClUrQjdwTHNPT0h5aVY2Mk5hbjBu
        Zmwwc3hpYUNkVTEreWx0RTMyU0EraDgKLS0tIFQwNThsdEJqMDlPU00xMWRTcmZQ
        TmRmMEdzTGdtRFNXQUZibjdqZ2RJaWsK+CbytSgRz0YyE3uhudj3J/DPgpjNGynB
        fL7jB944AK/IHfyQzg7ET2M4tmpuRZ/HchuB2/MF8588leL6YhNaAQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrejI2YmxDVEpDcVV5Q2wr
        Q0pzUTV3UjJ0dWVKTXI5Znk3dkVFRjJ3b0hZCkpqRlpEeHBaZnRoTXFBSzMxUnZG
        NXdTNFowOWk3UDBENWVzVXNMWkl6RjgKLS0tIEtoR1JUZTgrTEI5WEg0bUxnUVl5
        ZnJHQmpld1paQ1ZQZEZBRnZzcEdERTQKZwt9Ag1gAdT1a7pdBUsxblzpKP4cxckn
        jAyHNw53dZ9voMUUPJz797xVXTQxjFZAiMH2V3cXUzTln2C6nynAZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T07:29:10Z"
  mac: ENC[AES256_GCM,data:1eslsVsj2vnzOKpuHtzlvxihpl5bn7uffX3teE2bCqZWW2t0NlAEi5E9Tojegte9QjTImt0gYlOnDODfOX7/2YYd9CzPz4mx/npY+e8+8ZGpcCiFscYhj/IPjjTiqt5LltIG7hhXqci/alrr1nDRHe39i0q5gk09H0DaEU8Sb4g=,iv:tNA0JX2DNqXPKD+pKXBZd+p5nbqLczGiJvLY4Cpxa0U=,tag:k187IgoCgelAlSP9QfCwLQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
