apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    includeCRDs: true
    namespace: kube-system
    version: 1.16.3
    valuesFile: values.yaml
