apiVersion: v2
name: snappymail
description: SnappyMail webmail for docker-mailserver
dependencies:
  - name: app-template
    version: 5.3.0
    repository: oci://ghcr.io/bjw-s-labs/helm
type: application
version: 1.0.0
