apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: Wireguard
metadata:
    name: wireguard
spec:
    serviceType: NodePort
    port: ENC[AES256_GCM,data:SgjFcdA=,iv:BYKPQM8rZfVveQlGZHwmiLj4lZbRAXUFboh4aJj2z8o=,tag:oiC0IWK12x82C01UzKJJoQ==,type:int]
    address: ENC[AES256_GCM,data:iojlX4R18CPKtlwMgA==,iv:X+vpEgyHKdrnxQfNahQ4MM8JxfqLZtJO9zTw1/Sdvsg=,tag:e1zVdlwFspt9MhhxHE9RMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY0R1czNzZlFhM2R4MVpr
            c1l5bStzckZvTHBPdUxYQzVOSkozaDB4U2lJCjZnOCs5L3Z5KzJqZmVaS2cvU1hj
            cUwxL3RqamRvcS9tMGQwOG5sV0RnOXcKLS0tIElDNmZRbHZWRXpLVWduTDdUblRO
            bk00NXBFQkExN3A4WFZCbTZ6OEF0NlEKk1WagftL2CcoZFkRfq3zNC6LNSsS8a5l
            FGVl22Z2Re0C6KtRWprkvAzdD4v0ZhOdKdR85p0nkMW69bl0bufsAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T12:37:07Z"
    mac: ENC[AES256_GCM,data:CQ56Dn9MsZ7/25TGiQQcs2uGzkz/myJ7OLV4iLxY1ANv65K04a94YIZf1fJPj76aJ1bpyCs5RynP/4HoNXV7I7D5wjLc39rKTuaPF5NS0GbRdLtuVwFsfnNmlAenFxaVnjjSo7AeJk1ilcbqMkBBdapQzzBOyQkB9Q+wMFRaOpE=,iv:6uRKirlKRMd42nj7RPCJhy2bY+WAt8jcXomDWT4DVBk=,tag:MJvjdnHzjX975zCB6FBQwQ==,type:str]
    pgp: []
    encrypted_regex: ^(address|port)$
    version: 3.9.3
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: wireguard
    namespace: wireguard
spec:
    jobLabel: wireguard
    selector:
        matchLabels:
            app: wireguard
    namespaceSelector:
        matchNames:
            - wireguard
    endpoints:
        - port: ENC[AES256_GCM,data:giIH8O076A==,iv:/d5ic8KYLqkd2Kb6Vl2BUwjZs0QvRTI574rAJmUhZ7Q=,tag:kLISf7yjxudIEHcBrRwahQ==,type:str]
          interval: 30s
          path: /metrics
          honorLabels: true
          scheme: http
          scrapeTimeout: 30s
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY0R1czNzZlFhM2R4MVpr
            c1l5bStzckZvTHBPdUxYQzVOSkozaDB4U2lJCjZnOCs5L3Z5KzJqZmVaS2cvU1hj
            cUwxL3RqamRvcS9tMGQwOG5sV0RnOXcKLS0tIElDNmZRbHZWRXpLVWduTDdUblRO
            bk00NXBFQkExN3A4WFZCbTZ6OEF0NlEKk1WagftL2CcoZFkRfq3zNC6LNSsS8a5l
            FGVl22Z2Re0C6KtRWprkvAzdD4v0ZhOdKdR85p0nkMW69bl0bufsAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T12:37:07Z"
    mac: ENC[AES256_GCM,data:CQ56Dn9MsZ7/25TGiQQcs2uGzkz/myJ7OLV4iLxY1ANv65K04a94YIZf1fJPj76aJ1bpyCs5RynP/4HoNXV7I7D5wjLc39rKTuaPF5NS0GbRdLtuVwFsfnNmlAenFxaVnjjSo7AeJk1ilcbqMkBBdapQzzBOyQkB9Q+wMFRaOpE=,iv:6uRKirlKRMd42nj7RPCJhy2bY+WAt8jcXomDWT4DVBk=,tag:MJvjdnHzjX975zCB6FBQwQ==,type:str]
    pgp: []
    encrypted_regex: ^(address|port)$
    version: 3.9.3
