client_secret: ENC[AES256_GCM,data:vF3n8i85/oITAryVNMuXuw5CiSWiuoxuTX6yTjeIcvNbW2sOT+HGhz85XYY=,iv:AmPe3ZNfkDYSBIG0OCO7BT5S8MOuzh5xw1YWFXGAH7Y=,tag:8WxB62Kbz3rgdX3YlQPWfQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvM3c0UkdZL2FHQjFnZmhx
        QjNva1JsVXJvWmZ1citZZkxpdVl3UjAyMUdrCmFyTHpxZjRGUm9LR3JhdWI4MEhi
        L0E3R3hpeW9kMzY4R1BZcCtyTkxYZzQKLS0tIFFBQVBHN2JYOXpjWml0UFJXa2Zv
        b2QrQ2hackVXUFhrN2J0eGJvWWs2Y0EKba6H4yV+GK0khi6w9YmqCw/XqxESOzCC
        rgFzvT/1k/V1SG//YMDPjje3+X5uYpx3g2aLfD4QyRH21ysfzv5smQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdE5nRDBHdWo1Y1FBSmdu
        aW1wMUpDVGxpWnZZZWFBRVhtV1dLT1NYcTJjClZmTzBvaFdPNSszd05lcHpCOXlv
        UmRJT0Q5OXFITWZ2VG9WbGJkRFFaOFUKLS0tIGRDcFY2YmprSE1sVCs1ZUF5WitF
        MEFYVjZIck5PQ09SeVpiNjAvL0MzdXMK75hPUqOBSd9bZTTWGmTcFUV+nJk4QOy8
        YBhzLPH/EawvSagsjnWfRfrXkZGCX8tVha72Vg1QdHPE0DjrOnXznQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-07-29T07:13:51Z"
  mac: ENC[AES256_GCM,data:uk6CqsWBc0/UZEUL281i+jm6mp3JryaIUDUPtNDMU13U+sqrkk1ypWgXcopecpSe8p408KExfJqC+epDTfevrtLbSeGvxyvS528y9Xvpw7RkaOdLJmRPcBLiqbjXSB+cAM6bmdvwYgUP6Uq2Ge7QHu32G8TgxZLigUuYBq0g1UI=,iv:ms4PsyMIYstgOnP2jm4n/ecP3fZ9qNiVd3Tj6vaP778=,tag:ks3zLco80NdRO2r9R47BTw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.2
