apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: in-cluster
      namespace: argo-cd
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - https://github.com/Blarc/home-k8s
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: argo-cd
  source:
    repoURL: https://github.com/Blarc/home-k8s
    targetRevision: main
    path: 'kubernetes/argo-cd'
#    plugin:
#      name: kustomized-helm
  destination:
    name: in-cluster
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

