apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: .
helmCharts:
  - releaseName: argo-cd
    name: chart
    includeCRDs: true
    namespace: argo-cd
resources:
  - resources/argo-cd.yaml
  - resources/kube-system.yaml
generators:
  - resources/secret-generator.yaml
