apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    includeCRDs: true
    namespace: argo-cd
    version: 7.6.5
    valuesFile: values.yaml
resources:
  - namespace.yaml
  - projects/argo-cd.yaml
#  - projects/kube-system.yaml
generators:
  - secrets/secret-generator.yaml
