argo-cd:
  fullnameOverride: argo-cd
  namespaceOverride: argo-cd
#  global:
#    domain: argo-cd.apps.kubetest-ai.int.medius.si
#  server:
#    ingress:
#      enabled: true

  dex:
    enabled: false
  configs:
    cm:
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#auto-respect-rbac-for-controller
      resource.respectRBAC: "strict"
      kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
  repoServer:
    env:
      - name: XDG_CONFIG_HOME
        value: /.config
      - name: SOPS_AGE_KEY_FILE
        value: /.config/sops/age/keys.txt
    # Use init containers to configure custom tooling
    # https://argoproj.github.io/argo-cd/operator-manual/custom_tools/
    initContainers:
      - name: install-ksops
        image: viaductoss/ksops:v4.3.2
        command: ["/bin/sh", "-c"]
        args:
          - echo "Installing KSOPS...";
            mv ksops /custom-tools/;
            mv kustomize /custom-tools/;
            echo "Done.";
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
    volumes:
      - name: custom-tools
        emptyDir: { }
      - name: sops-age
        secret:
          secretName: sops-age
    volumeMounts:
      - mountPath: /usr/local/bin/kustomize
        name: custom-tools
        subPath: kustomize
      - mountPath: /usr/local/bin/ksops
        name: custom-tools
        subPath: ksops
      - mountPath: /.config/sops/age
        name: sops-age
