# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # secret files using GCP KMS to encrypt the stored PGP keys
  - path_regex: kubernetes/clusters/.*/secrets/sops-gpg.encrypted.ya?ml
    encrypted_regex: ^(data|stringData)$
    unencrypted-regex: ^(description|metadata)$
    age: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  # Kubernetes secret files using SOPS
  - path_regex: kubernetes/.*/*.enc.ya?ml
    encrypted_regex: ^(data|stringData)$
    unencrypted-regex: ^(description|metadata)$
    age: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  # Talos secret files using SOPS
  - path_regex: talos/.*/.*.enc.ya?ml
    encrypted_regex: '((?i)(pass|secret($|[^N])|ca|crt|key|token|^data$|^stringData$))'
    age: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
