# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # Kubernetes secret files using SOPS
  - path_regex: kubernetes/.*/*.sops.ya?ml
    encrypted_regex: ^(data|stringData)$
    unencrypted-regex: ^(description|metadata)$
    age: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  # Talos secret files using SOPS
  - path_regex: talos/talsecret.sops.ya?ml
    encrypted_regex: '((?i)(pass|secret($|[^N])|ca|crt|key|token|^data$|^stringData$))'
    age: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  - path_regex: talos/*/.*sops.ya?ml
    age: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  - path_regex: kubernetes/.*/*.ya?ml
    encrypted_comment_regex: "[:space:]*encrypt"
    key_groups:
      - age:
          - age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
    stores:
      yaml:
        indent: 2
