apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: wireguard
  namespace: {{ .Release.Namespace }}
spec:
  jobLabel: wireguard
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      honorLabels: true
      scheme: http
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: wireguard
