apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-policy
  namespace: {{ .Release.Namespace }}
data:
  policy.hujson: |-
    {
      "groups": {
        "group:admin": [
          "jakob@"
        ],
        "group:cod2": [
          "blarc@",
          "rokk@",
          "davids1@",
          "matejp@",
          "tilenp@",
          "markb@",
          "gregorz@",
          "janb@",
          "anzeh@",
          "janb1@",
          "simonk@",
          "aljazs@"
        ]
      },
      "tagOwners": {
        "tag:subnet-router": [
          "group:admin"
        ]
      },
      "hosts": {
        "lan": "192.168.1.0/24",
        "cod2": "192.168.1.224/32"
      },
      "autoApprovers": {
        "routes": {
          "192.168.1.0/24": [
            "tag:subnet-router"
          ]
        }
      },
      "grants": [
        {
          "src": [
            "group:admin"
          ],
          "dst": [
            "lan"
          ],
          "ip": [
            "*"
          ]
        },
        {
          "src": [
            "group:cod2"
          ],
          "dst": [
            "cod2"
          ],
          "ip": [
            "*"
          ]
        }
      ]
    }
