# $schema: https://raw.githubusercontent.com/cert-manager/cert-manager/refs/heads/master/deploy/charts/cert-manager/values.schema.json

global:
  leaderElection:
    namespace: cert-manager

crds:
  enabled: true

replicaCount: 1

namespace: cert-manager

config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true

prometheus:
  enabled: true
  servicemonitor:
    enabled: true

extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53

#webhook:
#  hostNetwork: true
#  securePort: 10260
