---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  # https://github.com/grafana/helm-charts/pkgs/container/helm-charts%2Fgrafana
  url: oci://ghcr.io/grafana/helm-charts
