apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lvm-disk-watcher
spec:
  interval: 30m
  chart:
    spec:
      chart: lvm-disk-watcher
      version: 2.3.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  #language=yaml
  values:
    configmap:
      disk-config:
        enabled: true
        data:
          disk-config: |
            control-plane-1: none
            worker-1: all
