---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-registry
spec:
  interval: 30m
  chart:
    spec:
      chart: docker-registry
      version: 2.2.3
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  #language=yaml
  values:
    persistence:
      enabled: true
      size: 5Gi
