radar:
  fullnameOverride: radar
  resources:
    requests:
      cpu: 25m
      memory: 256Mi
  timeline:
    storage: sqlite
  httpRoute:
    enabled: true
    parentRefs:
        - name: internal
          namespace: traefik
    hostnames:
      - radar.blarc.my.id
