apiVersion: v2
name: netbird-relay
description: A Helm chart for netbird-relay
dependencies:
  - name: app-template
    version: 5.0.1
    repository: oci://ghcr.io/bjw-s-labs/helm
type: application
version: 1.0.0