apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: Wireguard
metadata:
    name: wireguard
spec:
    serviceType: LoadBalancer
    address: ENC[AES256_GCM,data:iojlX4R18CPKtlwMgA==,iv:X+vpEgyHKdrnxQfNahQ4MM8JxfqLZtJO9zTw1/Sdvsg=,tag:e1zVdlwFspt9MhhxHE9RMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY0R1czNzZlFhM2R4MVpr
            c1l5bStzckZvTHBPdUxYQzVOSkozaDB4U2lJCjZnOCs5L3Z5KzJqZmVaS2cvU1hj
            cUwxL3RqamRvcS9tMGQwOG5sV0RnOXcKLS0tIElDNmZRbHZWRXpLVWduTDdUblRO
            bk00NXBFQkExN3A4WFZCbTZ6OEF0NlEKk1WagftL2CcoZFkRfq3zNC6LNSsS8a5l
            FGVl22Z2Re0C6KtRWprkvAzdD4v0ZhOdKdR85p0nkMW69bl0bufsAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T17:43:15Z"
    mac: ENC[AES256_GCM,data:QTzlbeEAAjKUp0JeQE/2WdFj9HlAkM0RzNvatxEx/w4zZdLQi2eQUBSWPSKfBVAIt91kKCyMPnFp2aY+CQiF+5wOfw+dp2ecXX/d9JGHlxGrFDBq/mSybIbwH7PLPG9Us71TWnXZOVEvBNuMMQ3xWqKPi9L/SN4Zx5NV6+hAwVw=,iv:2AvGctFUSsmHPLVVEvhAyt+DYwgRdYp5uh0huSf9rck=,tag:JstHkvb7lWVXUQtl+WxWVg==,type:str]
    pgp: []
    encrypted_regex: ^(address|port)$
    version: 3.8.1
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: wireguard
    namespace: network
spec:
    jobLabel: wireguard
    selector:
        matchLabels:
            app: wireguard
    namespaceSelector:
        matchNames:
            - network
    endpoints:
        - port: ENC[AES256_GCM,data:giIH8O076A==,iv:/d5ic8KYLqkd2Kb6Vl2BUwjZs0QvRTI574rAJmUhZ7Q=,tag:kLISf7yjxudIEHcBrRwahQ==,type:str]
          interval: 30s
          path: /metrics
          honorLabels: true
          scheme: http
          scrapeTimeout: 30s
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY0R1czNzZlFhM2R4MVpr
            c1l5bStzckZvTHBPdUxYQzVOSkozaDB4U2lJCjZnOCs5L3Z5KzJqZmVaS2cvU1hj
            cUwxL3RqamRvcS9tMGQwOG5sV0RnOXcKLS0tIElDNmZRbHZWRXpLVWduTDdUblRO
            bk00NXBFQkExN3A4WFZCbTZ6OEF0NlEKk1WagftL2CcoZFkRfq3zNC6LNSsS8a5l
            FGVl22Z2Re0C6KtRWprkvAzdD4v0ZhOdKdR85p0nkMW69bl0bufsAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T17:43:15Z"
    mac: ENC[AES256_GCM,data:QTzlbeEAAjKUp0JeQE/2WdFj9HlAkM0RzNvatxEx/w4zZdLQi2eQUBSWPSKfBVAIt91kKCyMPnFp2aY+CQiF+5wOfw+dp2ecXX/d9JGHlxGrFDBq/mSybIbwH7PLPG9Us71TWnXZOVEvBNuMMQ3xWqKPi9L/SN4Zx5NV6+hAwVw=,iv:2AvGctFUSsmHPLVVEvhAyt+DYwgRdYp5uh0huSf9rck=,tag:JstHkvb7lWVXUQtl+WxWVg==,type:str]
    pgp: []
    encrypted_regex: ^(address|port)$
    version: 3.8.1
