apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: Wireguard
metadata:
    name: wireguard
spec:
    mtu: "1380"
    serviceType: LoadBalancer
    address: ENC[AES256_GCM,data:iojlX4R18CPKtlwMgA==,iv:X+vpEgyHKdrnxQfNahQ4MM8JxfqLZtJO9zTw1/Sdvsg=,tag:e1zVdlwFspt9MhhxHE9RMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY0R1czNzZlFhM2R4MVpr
            c1l5bStzckZvTHBPdUxYQzVOSkozaDB4U2lJCjZnOCs5L3Z5KzJqZmVaS2cvU1hj
            cUwxL3RqamRvcS9tMGQwOG5sV0RnOXcKLS0tIElDNmZRbHZWRXpLVWduTDdUblRO
            bk00NXBFQkExN3A4WFZCbTZ6OEF0NlEKk1WagftL2CcoZFkRfq3zNC6LNSsS8a5l
            FGVl22Z2Re0C6KtRWprkvAzdD4v0ZhOdKdR85p0nkMW69bl0bufsAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T18:02:23Z"
    mac: ENC[AES256_GCM,data:PPNyT/zujAkp84vwQJKbPeH07aKi0Xv5rs9/7XCdeb73jC6DnNme3nEQPd2bakGYXAO7vZekE1QaZPOnl88Wd6v/OzlaOehqLz57FqBSmPBUKMemXeJjykqWkDLFlhuyxwtx/mmX5TkcU9J4SnMf5NDjpD8ONATDMf/9PBfV1k0=,iv:/lYN0Fime9GR6StVrlA0fCEGMUbNjPRWEUKQA9uOOVc=,tag:4i7aDb0IuL71vDYFivMXXQ==,type:str]
    pgp: []
    encrypted_regex: ^(address|port)$
    version: 3.8.1
