# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # Kubernetes secret files using SOPS
  - path_regex: .*.yaml
    encrypted_regex: ^(stringData)$
    age: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
