app-template:
  controllers:
    headscale:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        app:
          image:
            repository: ghcr.io/juanfont/headscale
            tag: v0.29.2
          args:
            - serve
          ports:
            - name: http
              containerPort: &httpPort 8080
              protocol: TCP
            - name: metrics
              containerPort: &metricsPort 9090
              protocol: TCP
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /health
                  port: http
                initialDelaySeconds: 5
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 5
            readiness: *probes
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi

  defaultPodOptions:
    securityContext:
      seccompProfile:
        type: RuntimeDefault

  service:
    app:
      controller: headscale
      ports:
        http:
          port: 80
          targetPort: *httpPort
        metrics:
          port: 9090
          targetPort: *metricsPort

  route:
    app:
      hostnames:
        - headscale.blarc.my.id
      parentRefs:
        - name: external
          namespace: traefik
      rules:
        - backendRefs:
            - identifier: app
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /

  persistence:
    config:
      type: configMap
      name: headscale-config
      globalMounts:
        - path: /etc/headscale/config.yaml
          subPath: config.yaml
          readOnly: true
    oidc:
      type: secret
      name: headscale-oidc
      defaultMode: 0440
      globalMounts:
        - path: /secrets/oidc/client_secret
          subPath: client_secret
          readOnly: true
    run:
      type: emptyDir
      globalMounts:
        - path: /var/run/headscale
    data:
      type: persistentVolumeClaim
      storageClass: topolvm-thin-retain
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /var/lib/headscale
