app-template:
  controllers:
    bazarr:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        app:
          image:
            repository: ghcr.io/home-operations/bazarr
            tag: 1.6.0@sha256:cd63bbd0986c93e238eb8b9442604d249f0d4080099b389f822abe2062044417
          env:
            TZ: Europe/Ljubljana
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: &containerPort 6767
                initialDelaySeconds: 10
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 5
            readiness: *probes
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: [ "ALL" ] }
          resources:
            requests:
              cpu: 10m
            limits:
              memory: 1Gi
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
  service:
    app:
      ports:
        http:
          port: &port 80
          targetPort: *containerPort
  route:
    app:
      hostnames:
        - "{{ .Release.Name }}.blarc.my.id"
      parentRefs:
        - name: internal
          namespace: traefik
      rules:
        - backendRefs:
            - identifier: app
              port: *port
          matches:
            - path:
                type: PathPrefix
                value: /
  persistence:
    config:
      type: persistentVolumeClaim
      storageClass: topolvm-thin
      accessMode: ReadWriteOnce
      size: 256Mi
    media:
      existingClaim: qbittorrent-media
      globalMounts:
        - path: /media
    tmp:
      type: emptyDir
