turn:
  username: ENC[AES256_GCM,data:qklLioNb+g==,iv:jj+aRQ4hi1aHZo6KQxY5QykML8UnFdHqzrC8wu3Cz1Q=,tag:i4Nfx276PqxW2ALjOO0ViA==,type:str]
  password: ENC[AES256_GCM,data:jQ7LvgwQ3rJy1im6cdrNoSzjAlCvX3I=,iv:Xa92o2NRbweL9P7SK5iNhFgZCUThUSXAqvZ6s8c0+qU=,tag:koy2u3+9HHUbAweQ/aiXUA==,type:str]
relay:
  secret: ENC[AES256_GCM,data:hwDlTu8C7MRaqwStlt201muQFvI9Gnw=,iv:gWoWGjEJsmKsk57jToYaLKOLZsQwMzwa1yNGnertd+g=,tag:xr2+PLyeTHrrhBJ+qH79yg==,type:str]
datastore:
  #ENC[AES256_GCM,data:4cauj+KQmvmFaoakMcmsFT0jWcFNdEwx,iv:TVJuwXJcci8TR41Awhsnnp+HiOhVZR698wx9aqIE2nk=,tag:XlZJ0nglHVnFby1s7nz6Jg==,type:comment]
  encryptionKey: ENC[AES256_GCM,data:JyKuK/WXGRDpYojwlgJH2BgPYwyvgT8CbF4ujsz34beEgJ+Bo8DfmD9SQTQ=,iv:mu5VDnBYKCI3HXoSMGmmkRJHGz9i8XNSsYqSn+WDd5M=,tag:zMuKfn/H+Bg4VsbNqbAI8g==,type:str]
auth:
  clientId: ENC[AES256_GCM,data:Pqqi9mUVMJQzVdbrBUBnOaNh4hy2e/VkzNQJOopWmH39MsJC18LLIg==,iv:/B4KRDCyuf4zHiFqcFDmqU+ZDiM7OEu3iRUKEqj2NzY=,tag:2VFRSDZ2jP50Ep78sXyZsA==,type:str]
  clientSecret: ENC[AES256_GCM,data:xGuloAymIm6xkwMZsPk9mkntUPMklTMpktB+HK/6NvRBojVgVHrB2oFhRv6UQeXlAjY2ctQkbQpQVg5F+k7/zDgi3gnPCdGMqAXSke19uUuOehV7j9aUColgw+YpLsby662fZUD6j7Hq9E3UlWoSa3U73aZlSC/6Z3/QBFn1lGM=,iv:Fhc3+BYXjKSorPJ3x33Ua8Rj1GKVlZabuVIL/eyorIY=,tag:X7+jq5GiQMEAonH4CEWjNA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT05LWWwreXJPeDJPRmd1
        VDRPQWd1YVo0YjRWaWVpb0ttMXduNUFia1FFCjFydVlLQU5RK0kvTXlUNWl4TlM0
        eG1IWHA1RGpvK2l3WlVaVVhLdkNhRUUKLS0tIFVPTlR4cHN6ZTNEQ1JyTHhRaDQ2
        MTZkdHhEb0lid0tZbm1MeVRqZWpZajgKqPOOkGFaemOq+ul4Vq12h/jQkkRqXWnk
        tQ31XqO+KaIi6hJ6Fkwo/qNFJsiBLvtaCy2OhtzqVzNOH32dvNKXHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aThoeW0vRmRlSHh3cDVu
        bjlPOGdydGlpVnJBUHBwQ2t3WlE1R29zRkhjCjFxemx2Y3ZiSm5idlBUdWxCOVRQ
        dHpVUmlHY1lpc2xkZDdhckpaRFNYb2sKLS0tIFc1M2dZV3FiaW0wNHdPVHVYZVln
        dkJPMXlqdm1kY0ZqMTN2TDNXNTJXcVkKpDgOx0IWi8Q/h8WYwpA82iT38JS9/oyM
        xStyF9trChR4RuvHTcRuedK+tnDJF1GhHqdPNVZ/C2fFxnBDSKJXlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-05-29T20:48:13Z"
  mac: ENC[AES256_GCM,data:Qq2gqihf0SengHBVjShJkAcyDOFMDrvSACzEJT4Fu36hHoel9I2oXozNV4bAABFOJn3HM/TlCyJImUXt+tT46N5rPETGcKnwIaw5sW+iDthUXirFl/es3SWMVJIdBW/UjYHno/6bwq+0MlH8A3AjueIstoDJBi50lPQlNpK/12g=,iv:bv9Rciv3FNK1xgYnvkvYFGW3XIhddbT3D3eb4CJn8oY=,tag:AuxN3QTpUwuSPWVrA0W2kw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
