apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager-webhook-etcd
    repo: oci://ghcr.io/blarc/cert-manager-webhook-etcd/charts
    includeCRDs: true
    namespace: cert-manager
    version: 0.1.0
    valuesFile: values.yaml
    releaseName: cert-manager-webhook-etcd
