app-template:
  controllers:
    unifi:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: ghcr.io/lemker/unifi-os-server
            tag: v1.2.0
          env:
            TZ: Europe/Ljubljana
            HOST_IP:
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            UOS_SYSTEM_IP: "unifi.blarc.my.id"
          securityContext:
            privileged: true
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/bash", "-c", "echo $HOST_IP host.docker.internal >> /etc/hosts" ]
          ports:
            - containerPort: 11084
              hostPort: 11084
              hostIP: 127.0.0.1
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /api/ping
                  port: 80
                initialDelaySeconds: 10
                periodSeconds: 60
                timeoutSeconds: 5
                successThreshold: 1
                failureThreshold: 3
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 4Gi
  defaultPodOptions:
    securityContext:
      seccompProfile:
        type: RuntimeDefault
  persistence:
    data:
      type: persistentVolumeClaim
      storageClass: topolvm-thin
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        unifi:
          main:
            - path: /persistent
              subPath: persistent
            - path: /var/log
              subPath: log
            - path: /data
              subPath: data
            - path: /srv
              subPath: srv
            - path: /var/lib/unifi
              subPath: unifi
            - path: /var/lib/mongodb
              subPath: mongodb
            - path: /etc/rabbitmq/ssl
              subPath: rabbitmq
  service:
    unifi:
      controller: unifi
      type: ClusterIP
      ports:
        webui:
          port: 443
          protocol: TCP
        rtp:
          port: 5005
          protocol: TCP
        id-hub:
          port: 9543
          protocol: TCP
        mobile-speedtest:
          port: 6789
          protocol: TCP
        communication:
          port: 8080
          protocol: TCP
        hotspot-secured:
          port: 8444
          protocol: TCP
        stun:
          port: 3478
          protocol: UDP
        syslog:
          port: 5514
          protocol: UDP
        discovery:
          port: 10003
          protocol: UDP
        support-files:
          port: 28082
          protocol: TCP
        aqmps:
          port: 5671
          protocol: TCP
        hotspot-redirect-0:
          port: 8880
          protocol: TCP
        hotspot-redirect-1:
          port: 8881
          protocol: TCP
        hotspot-redirect-2:
          port: 8882
          protocol: TCP
  route:
    dashboard:
      hostnames:
        - "unifi.blarc.my.id"
      parentRefs:
        - name: internal
          namespace: traefik
      rules:
        - backendRefs:
            - identifier: unifi
              port: 443
          matches:
            - path:
                type: PathPrefix
                value: /
