app-template:
  controllers:
    mongodb:
      forceRename: mongodb
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: docker.io/mongo
            tag: 8.3.2
          env:
            TZ: Europe/Ljubljana
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_USER: unifi
            MONGO_DBNAME: unifi
            MONGO_AUTHSOURCE: admin
          ports:
            - containerPort: 27017
              name: tcp
              protocol: TCP
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: tcp
            readiness: *probes
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
            capabilities:
              drop: [ ALL ]
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 1Gi
    unifi:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/unifi-network-application
            tag: 10.3.58
          env:
            PUID: "1000"
            PGID: "1000"
            TZ: Europe/Ljubljana
            MONGO_USER: unifi
            MONGO_HOST: mongodb
            MONGO_PORT: "27017"
            MONGO_DBNAME: unifi
            MONGO_AUTHSOURCE: admin
            MEM_LIMIT: "1024"
            MEM_STARTUP: "64"
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 3478
              name: stun
              protocol: UDP
            - containerPort: 10001
              name: discovery
              protocol: UDP
            - containerPort: 8080
              name: inform
              protocol: TCP
            - containerPort: 1900
              name: l2discover
              protocol: UDP
            - containerPort: 8843
              name: guest-https
              protocol: TCP
            - containerPort: 8880
              name: guest-http
              protocol: TCP
            - containerPort: 6789
              name: speedtest
              protocol: TCP
            - containerPort: 5514
              name: syslog
              protocol: UDP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: [ ALL ]
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 1Gi
  configMaps:
    mongo-init:
      data:
        #language=bash
        init-user.sh: |-
          #!/bin/bash
          set -euo pipefail

          if which mongosh > /dev/null 2>&1; then
            mongo_init_bin='mongosh'
          else
            mongo_init_bin='mongo'
          fi
          "${mongo_init_bin}" <<EOF
          use ${MONGO_AUTHSOURCE}
          db.auth("${MONGO_INITDB_ROOT_USERNAME}", "${MONGO_INITDB_ROOT_PASSWORD}")
          db.createUser({
            user: "${MONGO_USER}",
            pwd: "${MONGO_PASS}",
            roles: [
              "clusterMonitor",
              { db: "${MONGO_DBNAME}", role: "dbOwner" },
              { db: "${MONGO_DBNAME}_stat", role: "dbOwner" },
              { db: "${MONGO_DBNAME}_audit", role: "dbOwner" },
              { db: "${MONGO_DBNAME}_restore", role: "dbOwner" }
            ]
          })
          EOF
  defaultPodOptions:
    securityContext:
      seccompProfile:
        type: RuntimeDefault
  service:
    mongodb:
      controller: mongodb
      forceRename: mongodb
      type: ClusterIP
      ports:
        tcp:
          port: 27017
          protocol: TCP
    unifi:
      controller: unifi
      type: LoadBalancer
      ports:
        https:
          port: 8443
          protocol: TCP
        stun:
          port: 3478
          protocol: UDP
        discovery:
          port: 10001
          protocol: UDP
        inform:
          port: 8080
          protocol: TCP
#        l2discover:
#          port: 1900
#          protocol: UDP
#        guest-https:
#          port: 8843
#          protocol: TCP
#        guest-http:
#          port: 8880
#          protocol: TCP
#        speedtest:
#          port: 6789
#          protocol: TCP
#        syslog:
#          port: 5514
#          protocol: UDP
  persistence:
    init-script:
      type: configMap
      identifier: mongo-init
      defaultMode: 0755
      advancedMounts:
        mongodb:
          main:
          - path: /docker-entrypoint-initdb.d/init-user.sh
            subPath: init-user.sh
    tmp:
      type: emptyDir
      advancedMounts:
        mongodb:
          main:
          - path: /tmp
    data:
      type: persistentVolumeClaim
      storageClass: topolvm-thin
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        mongodb:
          main:
          - path: /data/db
    unifi-config:
      type: persistentVolumeClaim
      storageClass: topolvm-thin
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        unifi:
          main:
          - path: /config
