app-template:
  controllers:
    mongodb:
      containers:
        main:
          env:
            TZ: ENC[AES256_GCM,data:dOfoLjGHABCDkP4SRhQOaw==,iv:jCzXE16fg0855FmreVi33wovOzvaAVgIOwHI39Rqd0I=,tag:z5ln234Vd0FPrWb/SwFwlA==,type:str]
            MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:Yd1utp4cJivAY6CdDjVB5/I1M4WzHg==,iv:Cp+aMf0qq28KFHoKwD/43Kl7t88g/E/WbTFBO7GANgo=,tag:kt+P8lljEjpJqaS3h6AXjA==,type:str]
            MONGO_PASS: ENC[AES256_GCM,data:rrnJ8JDWVK64cUJij2rMTA3MKIQTFw==,iv:LnNDRkT8372Kuzte4lpq7TChqWYu+G8mOD2AUVqprUg=,tag:LXbTb4N98gEKO6d6zU1KpQ==,type:str]
    unifi:
      containers:
        main:
          env:
            MONGO_PASS: ENC[AES256_GCM,data:j0unNE+ogaJyrAtdaE2Eke66mt5qmA==,iv:z4DgAp/s5U6bUb40ZUkZRazL979JiF627qFV1mxaZHA=,tag:F8KQAyPV+nPrKPdEiTkSww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQlhLeDRvenJkVmpiTkhD
        ZXo1UzNHeWdOcmNVTW10eEx3cURMelc4UEFRCkhGOEkxWWI5STJnd0hVMnNkNDdT
        c0hFTHc3TnlqVlg2cStsNnZVQjVXMEkKLS0tIFNHalR5Q2RveTk3MjUrb0JVUHBY
        aXBmeU9OZHJoSWVSSlE0LzE1Ymh1K2sKtOSOER4wFrM/g3NHsD1SZxDnsQk/uHlH
        rKOZ3Gpr4wDt5JIjaAaTlgLfMroJt1Zsnie/8tanmQPTsWfZsxi0LQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbk9PUVRHQy9PbVRCVzVE
        RXF0cC9hSkVVemViK3MzQlNXcTRLdVgwQWwwClJJYmgwK2NhRUhWNndlL3VtaVVj
        c2ltN0JzN20yNE1wdldDTWoyMEYyQ3cKLS0tIGdyOFlJaUh0SHZFZERCMjV6MnVq
        RDBFSCtZUloyL3JJa3R5UitsMS92TFUKSaKqGT1i5Yn9itDc/wBF11cQUSHY4Fle
        bb4z26Jbcy0GjjkLLcr7hUe6xfJyeqc8pH6MxH6Jtw+VeCPmEQLvRQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-06-03T17:36:30Z"
  mac: ENC[AES256_GCM,data:U2msZ9KuFrb/9IzctQSictBhSqM1Zpnd+A2PryBxmR3eL8quBv1trH1SZZfhpvTWRMEK8VEuc4Xof48ppCtV9Xk56C/nzJk4qi3fJExrNkKaJSQKYUAl97xF48sTINqIdS1mIWuGBV6ZgsgepCtQxVTm1xHJpZIK1644E3XS8Ec=,iv:X5Hwt6pBKpIyEajtsQOR/KzsasO8aQjl4CeqUr4ABNY=,tag:z5P3ybq9z32E+VyIPC5mRA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
