# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable
---
version: 1
metadata:
  name: Paperless NGX
entries:
  - id: provider
    model: authentik_providers_oauth2.oauth2provider
    identifiers:
      name: blarc.my.id/paperless-ngx
    attrs:
      authorization_flow:
        !Find [
          authentik_flows.flow,
          [slug, "default-provider-authorization-implicit-consent"],
        ]
      signing_key:
        !Find [
          authentik_crypto.certificatekeypair,
          [name, "authentik Self-signed Certificate"],
        ]
      invalidation_flow:
        !Find [
          authentik_flows.flow,
          [slug, "default-provider-invalidation-flow"],
        ]

      client_type: confidential
      redirect_uris:
        - url: https://paperless.blarc.my.id/accounts/oidc/authentik/login/callback/
          matching_mode: strict

      access_code_validity: minutes=1
      access_token_validity: minutes=5
      refresh_token_validity: days=30

      sub_mode: hashed_user_id
      property_mappings:
        - !Find [
          authentik_core.propertymapping,
          [name, "authentik default OAuth Mapping: OpenID 'openid'"],
        ]
        - !Find [
          authentik_core.propertymapping,
          [name, "authentik default OAuth Mapping: OpenID 'profile'"],
        ]
        - !Find [
          authentik_core.propertymapping,
          [name, "authentik default OAuth Mapping: OpenID 'email'"],
        ]
  - id: application
    model: authentik_core.application
    identifiers:
      slug: paperless-ngx
    attrs:
      name: Paperless NGX
      group: storage
      meta_description: Storage for documents.
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/paperless-ngx.png
      provider: !KeyOf provider
      policy_engine_mode: any

  - id: policybinding
    model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf application
      user: !Find [authentik_core.user, [username, "akadmin"]]
    attrs:
      order: 1

  - id: policybinding
    model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf application
      user: !Find [authentik_core.user, [username, "jakob"]]
    attrs:
      order: 1
