# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable
---
version: 1
metadata:
  name: Users
entries:
  - id: jakob
    model: authentik_core.user
    identifiers:
      username: jakob
    attrs:
      name: Jakob
      password: !Env JAKOB_PASSWORD
      type: internal
      groups:
        - observability
        - media
  - id: masa
    model: authentik_core.user
    identifiers:
      username: masa
    attrs:
      name: Masa
      password: !Env MASA_PASSWORD
      type: internal
      groups:
        - media


