apiVersion: v1
kind: Namespace
metadata:
  name: topolvm
  annotations:
    argocd.argoproj.io/sync-options: 'Prune=false,Delete=false'
  labels:
    topolvm.io/webhook: ignore
    pod-security.kubernetes.io/enforce: privileged
