secrets:
    GEMINI_API_KEY: ENC[AES256_GCM,data:M2wOnYJE1Rg4aJisdNdt6VhY0NDDHN/pzM4HwDGptogfcni7CEtm,iv:UECg2pEDdv+JADWEQWKkV1Nt64se03Qr4nT2SHxYfWU=,tag:txeZJLPrkDZg4JQ6XaR7Jw==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:aw8ySH+7JE61CqLVj6mDs72gQUfdHeRgTA==,iv:p5nakoSJQY++mF+nU8CddM7S2J7vRQZ/zAap2vLk3gA=,tag:h1PHzuL/+jbdXfJTa8e4pg==,type:str]
    CLAWHUB_TOKEN: ENC[AES256_GCM,data:7Knpw1fvwKLTz4NX/B/rsj9WDULdbMB9PkGxiZYbZknijvvPE49c7XD/N+T3pu4=,iv:OQeTv7qQjwrem69ap+pBr97onqqL4wZ/gHx4A7fxv+g=,tag:RR0wnOxSkZwtmjMteVSMkg==,type:str]
    MOONSHOT_API_KEY: ENC[AES256_GCM,data:yqMi7cdPFjBLIYjgrIxgoNAHtxpo4DGIl9Wnd2NsYstNfiYWTTdSc/pmzEdS9hWZrB2tL4oV1X87il/EkkH40aqhSCz/+g==,iv:ovjtViWBX/ty2b9NZJZEitsBYeHt2mHu6llhzvjLThU=,tag:uBjvdcOQRrFTyF4umrfYcg==,type:str]
sops:
    age:
        - recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbk5rSGswUzBjYmZhaDk4
            MTVCRjJFSTlxampDWElxR0xQUWhMZm45akJRCkt6L2VRbXowNjFZOE1xeENYV014
            NkVDYW0yZ2V6MmhOYVBQZDFaTFFXelkKLS0tIHNZckY4YW1xUVZBck16eTV3aWg0
            Y29FK05hd0t2NUY4V2llOERTYUlJYncKpm5SFdxA49thDQzEJpu65o9l0k7W4ETd
            hrsXrU1CKDtxxS0EYMcwJnxRzqWmQ+oQwVtahUpyMhp97mQ++zRAPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMjdjVVB0YVRaa3FTV2pz
            VUFXMWpVRTVxN29TRCtLdk9lQjE1Uy9wMDNnClJLU1dLK1R2SDJTaUdzYXJqYnMr
            SjhaOTE4WGtDQ29RNGVBSUxSbng4NzQKLS0tIDFhbmRWUkpYeC80VkdpQ2ZOYXZp
            d1FsVzlIRGNkMFcvSXpqKytXUUZ1OTgKjNRYKxyXaJ7HU7EYt2bzkRBgyIoo9NlV
            0OUQpAjue0tp+gnFcBwFvzjlmI6Cuy0pbaXhz8ZLTWfq1y1Ec2LFSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T09:30:29Z"
    mac: ENC[AES256_GCM,data:4has2IJMY221bC2Ej/bYBd6oDZChIGnJeykjo+he0c0U+JD48Ac2wRoKOFrzSm9LBS1d0MTTcQTRroOIilkYm4+IN0cPr6wiulTuT3nm4aAj5DarJgXQejkkfoOivmSdtJyctCU4JgB/y/I0JConyr+OHhCtzCmMssHr+DwwUis=,iv:9IjqQU7pGYK5wzijHVSayEVry6A6htQXozVNLOgUBXA=,tag:epShm4PHkXHK11PWxlqhxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
