apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: etcd
    repo: oci://registry-1.docker.io/bitnamicharts
    namespace: etcd
    version: 12.0.4
    valuesFile: values.yaml
    releaseName: etcd
