apiVersion: v2
name: lingarr
description: A Helm chart for lingarr apps
dependencies:
  - name: app-template
    version: 5.1.0
    repository: oci://ghcr.io/bjw-s-labs/helm
type: application
version: 1.0.0
