node-feature-discovery:
  master:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 32Mi
  gc:
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
  worker:
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
