apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: coredns
    repo: https://coredns.github.io/helm
    includeCRDs: true
    namespace: coredns
    version: v1.36.1
    valuesFile: values.yaml
    releaseName: coredns
