apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: coredns
    repo: https://coredns.github.io/helm
    includeCRDs: true
    namespace: coredns
    version: 1.42.2
    valuesFile: values.yaml
    releaseName: coredns
