# isClusterService specifies whether chart should be deployed as cluster-service or normal k8s app.
isClusterService: false

serviceType: "LoadBalancer"

rbac:
  create: true

# Default zone is what Kubernetes recommends:
# https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options
servers:
  - zones:
      - zone: blarc.my.id
    port: 53
    # -- expose the service on a different port
    # servicePort: 5353
    # If serviceType is nodePort you can specify nodePort here
    # nodePort: 30053
    # hostPort: 53
    plugins:
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . 8.8.8.8 1.1.1.1
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
      - name: etcd
        parameters: blarc.my.id
        configBlock: |-
          fallthrough
          stubzones
          path /blarcdns
          endpoint http://etcd-headless.etcd.svc.cluster.local:2379
