apiVersion: v2
name: lldap
description: Helm chart to deploy LLDAP
dependencies:
  - name: app-template
    version: 5.0.1
    repository: oci://ghcr.io/bjw-s-labs/helm
type: application
version: 1.0.0
