app-template:
  secrets:
    crypto:
      forceRename: ENC[AES256_GCM,data:ORyVn5AYdord9AhE,iv:iSVzv7JCp2sS+li4KPQFu9St+xnw/pGFL8yb/Tt7Lzg=,tag:HgmA7U/CpsJTrbfbiaXS7g==,type:str]
      stringData:
        LLDAP_JWT_SECRET: ENC[AES256_GCM,data:qAOXQH5xyM4LN/QxWgwlf+BVtbxY/t3GZzlAOOPxhFWO3Elsw6fypUwYRUg/kRcZ6d7xEKY5G5oRIeh7hn7YLg==,iv:x+EbHkBsr1L4MF6Y8yIne+K2d2diraCrD3vK9ztZw98=,tag:qDcf3JprtiwmVr56LIZSxA==,type:str]
        LLDAP_KEY_SEED: ENC[AES256_GCM,data:U1AovELJsY9eE/nqyXW0EMu6wtXur5AnFCNPEXqZ0iNLp/OKcOnPsPfv905O3B5SUA52s1PZu6ws7Mtw62oB0Q==,iv:rs7W1LawCESKdWHSo5iQbT/EVsaoVNiRF/nww1TWfIA=,tag:A87XSXU5NE7NqyftMu495Q==,type:str]
    credentials:
      forceRename: ENC[AES256_GCM,data:TVZdhdxZI3IB2sod+lk4Cmk=,iv:hT4KcfDlNHdd5T+nCqE6gfwl9NZEvlhxcMkFuTVyU9c=,tag:YziE30JhflbS2v8i4ORmug==,type:str]
      stringData:
        LLDAP_LDAP_USER_DN: ENC[AES256_GCM,data:7Co+HIQ=,iv:oSwzziZc8ebMw8uQ1krQh/6B+rgwwmr3ZhNxRoTfwhw=,tag:EaPu2zrHTmrjTpX2NYgonw==,type:str]
        LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:m5kVVZIHfNfqxK11U6cY0XB/E1wYCpFSnurFaHBK720=,iv:Vq0JWtNBog0hjYhmxu26oJGta1aU3heL0VxofMjhQj8=,tag:ppE0Xe53XqG7QFZPYbdJsw==,type:str]
    smtp:
      forceRename: ENC[AES256_GCM,data:8omwR0Ff3vgcDRwUg0oSJA==,iv:Bme2PVofoH/6rucK932+92FNlYbGUGNKNgWmipzPBaI=,tag:+E2K3vrgJcpSGLjgx5BKWg==,type:str]
      stringData:
        LLDAP_SMTP_OPTIONS__USER: ENC[AES256_GCM,data:rp2nXv/KJB4ZH1IJpYKq7f+I9w==,iv:eQEfWhJKhhbo/T5lynHZCkX0clWnMTwVoCJimtHX75Q=,tag:wV90VBGtDRzgrSaNthDvwQ==,type:str]
        LLDAP_SMTP_OPTIONS__PASSWORD: ENC[AES256_GCM,data:GpL4so1N36uws4gzEt139OAhvWwBDNbX+MbhYvWWoBc=,iv:geUNnq0C6xcz6ldOfHc1spXcuwry5ys77yiazr7DUH4=,tag:tEd3WqTKZ8S5ugFl0BFoDQ==,type:str]
    bootstrap:
      forceRename: ENC[AES256_GCM,data:K1sstPUueqByJ67N5dQ/,iv:nyTKUnFUP+1gDdzYrKerEmTqVfqGR4zP+eryUOoLbgA=,tag:7fh0/3JJOhLXijgrvuRn3A==,type:str]
      stringData:
        groups.json: ENC[AES256_GCM,data:A9ePf8AI/1/+tXfP8T+tri4XokHCmi/tqEnMGDbEPJpDkhWMyYjMKYt2JGKPbzP/hcjyBJDCfuGIq1l6Rurpk7xltYsF6yH1XeUO,iv:5VpbLxPRj+iNyVeX4VAf0CHH/Sw1H9ZMR3ApezP5AKo=,tag:ZrKtgCPpviL5WOXMFdfNMA==,type:str]
        users.json: ENC[AES256_GCM,data:dKMGWKU1dY7IWOYzqk3uvpgm3NCL4HBfcZlpte1yNwhl2T9pKJu9dRm9GFOX/AfTC68047xEOU/qvfbzmhflIOqhJFcPR2njKPeaoGBRk87DRIG+M5rZUkKqjMPhrreuY7KpwyRtRbbBH8hBVWBFgXAlao57g4leMPyyMqiGQRncIpPX0tCqJCwbIZoGrSbHRlBGvyQT86zuVh5+GJ2wlA9k1R+Ip1SSKenu9p8R3CAtQUO+pprPe2VQ3QRvzAeXjQEjXlwi9GdeM15PzwQjhKy3J3e0YFiQLRVNvNYb7Dl3RJ1cb7MUYMZ/fqfnWSr5+u+pYftvb1cN/ez9kOh/mq0ac6tpabcW3JwkNaeGONevTzhoaCAKEQNCw1eb05ZkL3DYPmoEh6LZRki5fxUIvvjnJudRe9M+9JQ05YZOXpmMZqN1VYXvGEwdzHQvyyWp/3vfa2Sm+Kb1Mx/Sru8WyTE3sKZJxRVqGZFypUi1Mfyu+vSehartEB8aVhznIZ45R2NwHjGgR49DN7RzbqOaC01dD4YgbOQPy9FmmuVY1UMNS7jnBUPQFAAyAdrC8eEv8Mu1tHAECKgFD+WiEQadKs5wSEp3KV1gTtp2eaUCsME5dFBAS7c3XArcDFFIJkAxraj2nAJB4VqFcAcDmnqcbIISf2szbfYL17ylnReEgBWKZR1kv1giw86pE4DI53ApU8nzAPKlPN/q9mziKU3UkviEu/+NMDNezTk8NmzxIRSQebgKVTpUSyFDWJZY/ooUxt7NyFVd5UR8re6qhEXsl0ZH1A7R0+Zs1oR1Rh/o05bsbdD+RMKeIxmSS3D+S/rJgzVOfSw1ffXQITAWMJuXNgdwIm1hP70zpsEZ5Xt8cYapyX5vdOAqxETmEKNj+i+ko5NCWmtb8/5FXuPvdIrYEVNKuChakx4RNEGLbF8hhS/6TRUBd8vvSr19H7GIU8oZ+h60S7QS42W5/IU9opPgYUP6AdVVPM0Th2gLluJGvpd6oPymmfuvat2nDpNQPatdFvfa4+sG84C6TwNVv/0ySIbnrOClvWs7qgIhrObWk79GJG+EpITA2xAd7P9DEVbWSJOkIPiOIIaORv5xArdfjwq3CXCDjtMSLhd5SXfAqg8bwoi8a9dQmrMgri7wRiVHiHXWG3I+uiYEC3g2myR0/EtHPyY8rzkUJ30cIQCBetdfkNlSJfIX4UK4AK8EXGSg9DMjmdTXIvESBUIT6yKfxP0kRRXhxEAwXVs/UBRca70/FrnPK8oHpoCrB2RqCeWryGg=,iv:vhl1iwDcKC81EgSi0WWuC5yuBTsEofVAXh7l7g/UwpY=,tag:xWGroMPFGBdNxx1+a2FkAA==,type:str]
        user-schemas.json: ENC[AES256_GCM,data:grg=,iv:juXOBPtLF1crfB4jy0ICT4zdpFSmosKx2WrS+ypI7Ts=,tag:acK5+vxlWiWw/8caNujdaQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWmtLSjluMXhacnBsUkFE
        M0tFWUt0YmNhYUlBOElaUkJ6YkdMZ0V5dWc4CkY4YU5IOFpmYXkxQTNWR0ZwZlJy
        U2dic2Z5cElpM1lPV1BsMjZjT0hYMm8KLS0tIERnbTgrSjZEdDhZRGQ5R0dPS2NQ
        WGJQVWVPckN5ZElmTmQvM0d3UG02RncKot2zG6zE886EziGhaQK86AAILjL1Ew+b
        f95mIlcF2gd9zMre4hQp+QH8khj8c2QVVrdJwHCQq9xOZBTReWBWrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVTVFbnFFNGhqSmZvbm1K
        eDk2L0xFVjRQTDJPbmNRSkNlV3ViM0g4L0JVCitJUERyRzYxSDhsZTdzUzFxK0VG
        ak1hNTB6VnBpTkZNdy9UZjBFMy9jUTAKLS0tIHBCaG5LcStkdzVDeEZFSmNRSFBh
        VEhVd2xPQTllMkZVTzJ5dVhYRE1ldmsKvvSgk7NEl85S4m1DPH4ZRKoQKh0x/jPF
        nAjZ+Qpq4TwAubLtsiYXOkC17C0e9Rn6nwe7DT29qtm+QaDADagXag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-07-24T11:25:36Z"
  mac: ENC[AES256_GCM,data:OegH6clo//FAbr9ceK+KX566txRhXo37La2Z1gsKcW7zx0k0VkmqDFg/lwKsxLiPcMB57VspZ/S3wyg3R7Xd5vEUyUwFUJfm68Y7QwLjWOEg/yuRz/Pj1jtYrGxjGORrlhru+85S7uhT36CODnx8UTN0F7+nd5mtjA2IuGy+ty0=,iv:RrDdUQ68T5u1OZ6aFTp5f1liyckvAjF5w6iICunrAYc=,tag:4xN3PrgjElMHNApXFYBCKg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.2
