app-template:
  secrets:
    crypto:
      forceRename: ENC[AES256_GCM,data:ORyVn5AYdord9AhE,iv:iSVzv7JCp2sS+li4KPQFu9St+xnw/pGFL8yb/Tt7Lzg=,tag:HgmA7U/CpsJTrbfbiaXS7g==,type:str]
      stringData:
        LLDAP_JWT_SECRET: ENC[AES256_GCM,data:qAOXQH5xyM4LN/QxWgwlf+BVtbxY/t3GZzlAOOPxhFWO3Elsw6fypUwYRUg/kRcZ6d7xEKY5G5oRIeh7hn7YLg==,iv:x+EbHkBsr1L4MF6Y8yIne+K2d2diraCrD3vK9ztZw98=,tag:qDcf3JprtiwmVr56LIZSxA==,type:str]
        LLDAP_KEY_SEED: ENC[AES256_GCM,data:U1AovELJsY9eE/nqyXW0EMu6wtXur5AnFCNPEXqZ0iNLp/OKcOnPsPfv905O3B5SUA52s1PZu6ws7Mtw62oB0Q==,iv:rs7W1LawCESKdWHSo5iQbT/EVsaoVNiRF/nww1TWfIA=,tag:A87XSXU5NE7NqyftMu495Q==,type:str]
    credentials:
      forceRename: ENC[AES256_GCM,data:TVZdhdxZI3IB2sod+lk4Cmk=,iv:hT4KcfDlNHdd5T+nCqE6gfwl9NZEvlhxcMkFuTVyU9c=,tag:YziE30JhflbS2v8i4ORmug==,type:str]
      stringData:
        LLDAP_LDAP_USER_DN: ENC[AES256_GCM,data:7Co+HIQ=,iv:oSwzziZc8ebMw8uQ1krQh/6B+rgwwmr3ZhNxRoTfwhw=,tag:EaPu2zrHTmrjTpX2NYgonw==,type:str]
        LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:m5kVVZIHfNfqxK11U6cY0XB/E1wYCpFSnurFaHBK720=,iv:Vq0JWtNBog0hjYhmxu26oJGta1aU3heL0VxofMjhQj8=,tag:ppE0Xe53XqG7QFZPYbdJsw==,type:str]
    smtp:
      forceRename: ENC[AES256_GCM,data:8omwR0Ff3vgcDRwUg0oSJA==,iv:Bme2PVofoH/6rucK932+92FNlYbGUGNKNgWmipzPBaI=,tag:+E2K3vrgJcpSGLjgx5BKWg==,type:str]
      stringData:
        LLDAP_SMTP_OPTIONS__USER: ENC[AES256_GCM,data:rp2nXv/KJB4ZH1IJpYKq7f+I9w==,iv:eQEfWhJKhhbo/T5lynHZCkX0clWnMTwVoCJimtHX75Q=,tag:wV90VBGtDRzgrSaNthDvwQ==,type:str]
        LLDAP_SMTP_OPTIONS__PASSWORD: ENC[AES256_GCM,data:GpL4so1N36uws4gzEt139OAhvWwBDNbX+MbhYvWWoBc=,iv:geUNnq0C6xcz6ldOfHc1spXcuwry5ys77yiazr7DUH4=,tag:tEd3WqTKZ8S5ugFl0BFoDQ==,type:str]
    bootstrap:
      forceRename: ENC[AES256_GCM,data:K1sstPUueqByJ67N5dQ/,iv:nyTKUnFUP+1gDdzYrKerEmTqVfqGR4zP+eryUOoLbgA=,tag:7fh0/3JJOhLXijgrvuRn3A==,type:str]
      stringData:
        groups.json: ENC[AES256_GCM,data:A9ePf8AI/1/+tXfP8T+tri4XokHCmi/tqEnMGDbEPJpDkhWMyYjMKYt2JGKPbzP/hcjyBJDCfuGIq1l6Rurpk7xltYsF6yH1XeUO,iv:5VpbLxPRj+iNyVeX4VAf0CHH/Sw1H9ZMR3ApezP5AKo=,tag:ZrKtgCPpviL5WOXMFdfNMA==,type:str]
        users.json: ENC[AES256_GCM,data:oJJW+6z01/E0xLjSie6rcLXxrObqGn9aRLEX49PaUhJLY8x8yEN8hiHeOj9xeD55CAX49jftdLxerP6usjsNj2YIr92tOV/O9PfQ05irPdUVaAiuBimigvvnxAvU7JKOdaq68rmhmQDm6Y7i6lHVAZrhDXW7NaoIuyjeBHjSauojnUSLREdMpgjw+cYfIb84Tpj+fvg2gzs8tfYZnMiIP3As7rk98E4h50f+xclvquyWp5qaaZc3vmMfWYVqnyrftMOPPr/vmHQwBy0DATruJcr/PobR5PRyORArPzaOgdyi1BoGjqdtLcKlsgD9GacZizkPz5sX/9/fakJkyGuI/EFcu4ciW6IefUmaSZkePaVxmuwpsfflWjW/+VYlDMnqYnWxRCg3hmrWptdTpimSDobEy/TOMoJT5q7e8nH4JI6a8pg37+//QlBau5bDL5XuHGRoe65x87+R3Kf0QYklsqHJtzsr0Nox41TsqI85NZ/52Xwt6DA8iAS3LOm1d2uvwwsvE8jq2X8dNyY+sc7WIZ8XNawmKAszGTGOqBHt7WAKJYiNCt2dj5Tc2PA64DkLHuBQ17smX+X0/DdekFa/w5g6eVkiibI7SivtsJCl7zArSUSMtd5rUv73kajm/KJ/olu27BDPG8mc6ZZosQ1XFC0VuakYTHagQjAZTwvMWr5ZIIjgCwXywyWki1fZAEdfpJm6WhMx+6tJmH4CRkxvggDFykIGxkmrweEFClX/wZ4WvV5WRzCawYI7GqqhR1ic4oghEkz0/eK2rr3wSthAlJOlOHyNll5xVRRPeHHYJlesHHkZnz8DT3CAlCMmQs03aHdX8QnvHrrE9N1aoPgU5HUXz70ZbOJyBKu57ugMxTBiVTbAM07l+CF2BJdMGC2cPkY6ukwS/IQRnbjNOYuLtwmlWjD2csq1IehN55h1H+58Y9LfNLXusQ1uv9EZRFtuwnSIUISGsWmGR5BnIrCOXTjXyXcRecGL8cr7ZHaxL55iOpVSKEB5jZKwjT1g7uu34zlbMWFhnoECZvPW53V8VSjmd2U2Xk+IYczYVc/3xrYLkWMXi4JyNcp/ziZo4ysxDAVdm/lXUiN0wnTBws7J6r1uKEbU9kbN1JblIMcxIKKK3JslDQJOzRwYHp8dSsEcIGVwhluAIXsFcJWTxfjPHaKkIm07sDXCJ0qkoJIiF3fVGi+5QmJWTvOhnsPgZuKSGr8qpAqeCs5b6tNQaMESDILs/8qOiYYWlM8GxGUObf7iXm2a7lYnFDBX++KIPFWbSMMe0DDx9iT2tiIvKS7CZMbLB4brD3UP0EkKMplJ1XMqsqe7unWQ84du+1CAZfT8HcNYvnLH/+/c5RndRZg6ykPKlT54xWRvl2mQaCRtgjNShaIvRvqB4H8a/wGD7QqCuvJ9c8EC1B3IlTQk5dm1lWWV4fB0dwn8tfxFIajY697fz9K4zYP5GbPgBzuopJZUxh2hUNcEdP5O8E7HAotfzgRuD0ohYS/B5kxNxfvhJVJ2O83uvWAP7hiYdD6GW3mA1B7Sbh+GWsJcoPLfml1yAWf288Ht/zN+NufxXopyHaxrzsZXmJTZoCdeo6BVtC/wXVPMU/Ss8Z++BcFBUCz1tC/JW4cUycUxbtwYcyXbNaJUJJoDFVOHm7/4tm0tL5W/gjL2b20twnY4LC3KIC6GwYWpUgVk0bfjB5q0UUigdqMAq0aeVzeKqPRoNwJdhWv545g7IBf9bETiUykNJTaDoKROd0FoS0yv0mVpa8tiQ1Axt0ELBHbrwXQH3/6T7oX4pS480T3EHUKz8pEEhkDqiry75lnwsg==,iv:ZfX6Bun1JtcVINObruUUNctDzeUyPLJ4VtzbFYvc5ZA=,tag:eJq8tl1cRkPtg73AARj8ag==,type:str]
        user-schemas.json: ENC[AES256_GCM,data:grg=,iv:juXOBPtLF1crfB4jy0ICT4zdpFSmosKx2WrS+ypI7Ts=,tag:acK5+vxlWiWw/8caNujdaQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWmtLSjluMXhacnBsUkFE
        M0tFWUt0YmNhYUlBOElaUkJ6YkdMZ0V5dWc4CkY4YU5IOFpmYXkxQTNWR0ZwZlJy
        U2dic2Z5cElpM1lPV1BsMjZjT0hYMm8KLS0tIERnbTgrSjZEdDhZRGQ5R0dPS2NQ
        WGJQVWVPckN5ZElmTmQvM0d3UG02RncKot2zG6zE886EziGhaQK86AAILjL1Ew+b
        f95mIlcF2gd9zMre4hQp+QH8khj8c2QVVrdJwHCQq9xOZBTReWBWrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVTVFbnFFNGhqSmZvbm1K
        eDk2L0xFVjRQTDJPbmNRSkNlV3ViM0g4L0JVCitJUERyRzYxSDhsZTdzUzFxK0VG
        ak1hNTB6VnBpTkZNdy9UZjBFMy9jUTAKLS0tIHBCaG5LcStkdzVDeEZFSmNRSFBh
        VEhVd2xPQTllMkZVTzJ5dVhYRE1ldmsKvvSgk7NEl85S4m1DPH4ZRKoQKh0x/jPF
        nAjZ+Qpq4TwAubLtsiYXOkC17C0e9Rn6nwe7DT29qtm+QaDADagXag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-07-26T18:59:28Z"
  mac: ENC[AES256_GCM,data:DNYxWXhVde8Uqfpjc/Hq16uCP41X+rs0QQti+FQ5umdVnPBJWjA01Wiz20RvtGPMkr6lOttt21sLuEhcEd5YZtUH05xpthGHUrbp2XOV2hu0yACXimQ9+vVFFschH3iDpF8C1QhelNwj1n+VJk0N5chyN7jQChmFpLgBnXwF9V8=,iv:vSG2bWTevOMq92fz64JWQxXv/5wqb1fOjJ6sxI8iVFE=,tag:UeApX3B+UY9us8upKlc/zA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.2
