apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-etcd
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cert-manager-webhook-etcd
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-webhook-etcd-values
