app-template:
  controllers:
    radarr:
      containers:
        app:
          env:
            RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:nSspXzXo1KZVZcjNz/R+urZZoX7wVSDdTJwn4shc6Lk=,iv:WSQH6xZMkYTv4NVMWcioJ148zwEWEFXlUwXkiYVTZgc=,tag:e6BnGOUFepbqRStA9riWJA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSlc1cGREOHN4M0E0bVlY
        c3V2NGkwUUowb2Y2Yk10N0sxQU5vZWlsRzNRCnhkZTJ1anBpT2JueTJNQ05xbUZV
        UkxJVUhPSDlKNVFuaFAzcUpqWkx1d0kKLS0tIHd1a0xPajM3akloMjQ3bGtJdEtk
        cGxyb3lsV1JjZjU1dmlqVmFSWkk3M0EKt2bf2ag8fAM5sxfavNcjfwJ+i9bE/9UO
        bAEB8DoKSvIfYWqV8Hmm9YNtloD5e+i2s5PqDAqHHsMN9B9/D1K9Ug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aXI3RjdQQkVOOU5KMkJv
        cUt1K08vY2wvRlV5V2Z3azd5SjhqWnArcUdJCk4yK2I3c29iWlMram9HZ0VKU1NX
        QXY5THg4S0Q2ODMyTTY4UUpiWVNmYTAKLS0tIG9JS0NVTGNTdDdYbkF4Ritzbi9w
        VU5mQkRVaEZ6STZ0cjZCYzUvMmlLd0kKcK4D2i4WBj47KaabSpgZPY/XeCOk9B9s
        DO1w8Cq8V7Ng0xTQ+wKpEBaLZz/ekzyuaIp/9RA6aEXiJXnVX2Ch4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-07-15T17:50:44Z"
  mac: ENC[AES256_GCM,data:czenSLPM/Kdc9J2GLCkUZeVkQPrNTBIh5JUeLGoEWIcwmaPiYh2mp/yDkIBvD3rq7i0ah3wmp2Iqa7a+jEZhe0jBpijNxni1gpuHNQXa9TI/zpyBe1gTiRAldLy3CCFZpIzJ+w8ClOmidrUPFYmYbnchD1oHPxLzsR/EV7bOWoQ=,iv:KDxV3YOZrX/m0Wt7xXb3bKdWY7OK5D7LiGKIDZk6yTg=,tag:XVgPrssgLP78yU7fEGqaKw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.2
