docker-mailserver:
  fullnameOverride: docker-mailserver
  certificate: docker-mailserver-certificate
  configMaps:
    dkim-signing.conf:
      create: true
      path: rspamd/override.d/dkim_signing.conf
      data: |
        enabled = true;
        sign_authenticated = true;
        sign_local = true;

        domain {
          blarc.my.id {
            selector = "mail";
            path = "/etc/rspamd/dkim/rsa-2048-mail-blarc.my.id.private.txt";
          }
        }
  deployment:
    env:
      OVERRIDE_HOSTNAME: mail.blarc.my.id
      POSTFIX_MESSAGE_SIZE_LIMIT: "73400320" # 70 MiB total email size
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
        ephemeral-storage: 100Mi
      limits:
        cpu: 1
        memory: 1Gi
        ephemeral-storage: 500Mi
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      lbipam.cilium.io/ips: "192.168.1.225"
      external-dns.kubernetes.io/hostname: "mail.blarc.my.id"
