docker-mailserver:
  configMaps:
    postfix-accounts.cf:
      create: ENC[AES256_GCM,data:gfXMCg==,iv:tHzcRdlhsvM2YmLp8rMJpoQxfgMe46IlPm/hZ8CCxT0=,tag:wSNPEtO5e4FvYBn0isyDnw==,type:bool]
      path: ENC[AES256_GCM,data:ghAhhQvyiFmlwbPngSIN3xyW+g==,iv:IOlYFFVId/3Ghw82JOwMSuJg9cIxwVmVJtf43axORJo=,tag:qGfrDL7uc8SLTK49X1K3rw==,type:str]
      #ENC[AES256_GCM,data:varVrrwU6Qm7Q42rL2Ut1mXcLJ9lHU9pATl3wEvQrnAGZnYf7M6ePVDhcAH7,iv:OKAtyQH86xAvjCl3h/TOcE98K9sXYGcWEx+ar55JdcM=,tag:6ErUawT3j6yfKHkvpt2jIg==,type:comment]
      data: ENC[AES256_GCM,data:1ykUD7mS+SJDh8jyjYRPNH/yP/6InrIu4OPjR4R/2cShR/55sR+8wwzpQsfsSRcaokeiowcDzmZ6ThbSGJgSTYzUfNV77G3sZ3qmHEJZMzLUNZ+0lwZ2hsDpoVpvux3zF80aJmBcB68QoJEtOBvv4oj9g+Xoa99BIT6tbecMaXrhAJhfPw9GtqxXq3gx,iv:ilgn4Ob5K3ReaDstSM+I5c1NGWsf//YTKlzGNinx9cE=,tag:SpHRHifxJEBo01Q+eiJBCg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NFN2Y1ZFRmVwWGV1c0xw
        MUgzUG5MVUc5Z3Y5cFU0alpWUGRRdFN2VENjCkRIYkpFRVI0STU1NTl3cFlGUDJI
        ekVMSTNKQkZFcnJyUm12UlhqZXR1MjgKLS0tIFZDdGsyMlFpQ0JDdythK2g0UmJZ
        SmRaRXRRaDFwS1BuTkJkZjBmRkdNK00Koc23GYmxbW7xR5jN4I3KI0AkthZi8KsL
        eQf/ZRtTcdo+ArFJRaDBonlaI6mfpaZESdkIHVmOi9WUzkY3GQawuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeW5TcXpHUEpHQTlBUnYr
        b0lEdEV5MjZlYkEvck1RbE1JVzdFS2VkeUVBCkNuYW5LSUp4cGxLU25lallNTklx
        Sk54dWVIOUtEbnVYMkJXQ01xSmFZN0kKLS0tIGFva1JWS1RKendrRTZJL1poUDND
        TjNDcGxLOTlmb2FtTGNwZU5YNSs5OW8KJ66SBurqyYfJgrok4sVi3AvnDUTb/AOI
        9Ge1MvjQftbJpzfHqP3jDD1gZXQQ51FvJ40z37wo0DYz6Wq3x0dx2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-07-24T07:37:00Z"
  mac: ENC[AES256_GCM,data:n0tXHa/9R7lksdn4nj2NpXnUpuUiaL1Z4kxLIwUqorp4tw2wvlCr4kONPWUgnYAaNUelgOzF8mH3LawLKwXeDPehqfLJ7cOWnfJK3iyXJOvTZkBdgC6bLaj9AyY/mr34Zsjf6a65r5M1HIC0crCEChsglmpwcoX6xImRhanl6z0=,iv:YwxZVqZ0sM2j9yeDIi846unE1xW9Xvjje/21oV7V2rU=,tag:mup466yjSxkllyk9hlG+OQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.2
