apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
data:
  PAPERLESS_ADMIN_USER: "admin"
  PAPERLESS_URL: "https://paperless.blarc.my.id"
  PAPERLESS_REDIS: "redis://redis:6379"
  PAPERLESS_DBHOST: "postgres-rw"
  PAPERLESS_TIKA_ENABLED: "true"
  PAPERLESS_TIKA_ENDPOINT: "http://tika:9998"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://gotenberg:3000"
  PAPERLESS_OCR_LANGUAGE: "slv+eng"
