apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: paperless-ngx
spec:
  instances: 3
#  postgresql:
#    parameters:
#      max_connections: "200"
#      shared_buffers: "256MB"
#      effective_cache_size: "1GB"
#      work_mem: "4MB"
#      maintenance_work_mem: "64MB"
#      checkpoint_completion_target: "0.9"
#      wal_buffers: "16MB"
#      default_statistics_target: "100"
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
  storage:
    size: 10Gi
    storageClass: "topolvm-thin"
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
