app-template:
  controllers:
    libretranslate:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        app:
          image:
            repository: libretranslate/libretranslate
            tag: v1.9.6
          env:
            LT_PORT: &containerPort 5000
            LT_UPDATE_MODELS: true
            LT_LOAD_ONLY: en,sl
            TZ: Europe/Ljubljana
          probes:
            startup:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: *containerPort
                periodSeconds: 10
                failureThreshold: 180
            liveness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: *containerPort
                initialDelaySeconds: 60
                periodSeconds: 60
                timeoutSeconds: 5
                failureThreshold: 35
            readiness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: *containerPort
                periodSeconds: 30
                timeoutSeconds: 5
                failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: [ "ALL" ] }
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 2Gi
              cpu: 1
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1032
      runAsGroup: 1032
      fsGroup: 1032
      fsGroupChangePolicy: OnRootMismatch
  service:
    app:
      ports:
        http:
          port: &port 80
          targetPort: *containerPort
  route:
    app:
      hostnames:
        - "{{ .Release.Name }}.blarc.my.id"
      parentRefs:
        - name: internal
          namespace: traefik
      rules:
        - backendRefs:
            - identifier: app
              port: *port
          matches:
            - path:
                type: PathPrefix
                value: /
  persistence:
    models:
      type: persistentVolumeClaim
      storageClass: topolvm-thin
      accessMode: ReadWriteOnce
      size: 512Mi
      globalMounts:
        - path: /home/libretranslate/.local
    config:
      type: persistentVolumeClaim
      storageClass: topolvm-thin
      accessMode: ReadWriteOnce
      size: 256Mi
      globalMounts:
        - path: /home/libretranslate/.config
    tmp:
      type: emptyDir
