apiVersion: v1
kind: Namespace
metadata:
  name: observability
  annotations:
    argocd.argoproj.io/sync-options: 'Prune=false,Delete=false'
  labels:
    external: "true"
    pod-security.kubernetes.io/enforce: "privileged"
