---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - postgres.yaml
  - redis.yaml
  - secret-key.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: authentik-blueprints
    options:
      disableNameSuffixHash: true
    files:
      - ./blueprints/apps-paperless-ngx.yaml
  - name: authentik-values
    files:
      - values.yaml=./helm/values.yaml
configurations:
  - ./helm/kustomizeconfig.yaml
