apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: authentik
spec:
  instances: 3
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  storage:
    size: 1Gi
    storageClass: "topolvm-thin"
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
