trivy-operator:
  operator:
    scanJobsConcurrentLimit: 1
  trivy:
    # we probably do not need to retain it
    storageClassName: topolvm-thin
    # the default is 5Gi
    storageSize: "2Gi"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1
      memory: 1Gi
  serviceMonitor:
    enabled: true