---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app lvm-disk-watcher
  namespace: flux-system
spec:
  targetNamespace: lvm-disk-watcher
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/lvm-disk-watcher/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
  wait: false
  interval: 30m
  timeout: 5m
