apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - namespace.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    includeCRDs: true
    namespace: cert-manager
    version: v1.16.2
    valuesFile: values.yaml
    releaseName: cert-manager
