apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  # Specify a name
  name: test
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secrets/home-k8s-repo-secret.sops.yaml
