---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kepler
spec:
  interval: 30m
  chart:
    spec:
      chart: kepler
      version: 0.5.12
      sourceRef:
        kind: HelmRepository
        name: kepler
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    serviceMonitor:
      enabled: true
      namespace: "observability"
      interval: 30s
      scrapeTimeout: 5s
      labels:
        release: kube-prometheus-stack
      attachMetadata:
        node: false
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
