apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-key
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  BOUNCER_KEY_traefik: {{ required "crowdsec.bouncerKey is required" .Values.crowdsec.bouncerKey | quote }}
