app-template:
  controllers:
    relay:
      containers:
        app:
          env:
            NB_SETUP_KEY: ENC[AES256_GCM,data:NeAig1oeXvkdP6Dzrdg5L2UD3oBTtRfhi9g2,iv:Hf3Y7G2dJlF8Ma0Tl9Feb6PDnZVAxKrSJc8gAZzJylM=,tag:LqJ6StEP13rWHrXtOT+VHQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT05LWWwreXJPeDJPRmd1
        VDRPQWd1YVo0YjRWaWVpb0ttMXduNUFia1FFCjFydVlLQU5RK0kvTXlUNWl4TlM0
        eG1IWHA1RGpvK2l3WlVaVVhLdkNhRUUKLS0tIFVPTlR4cHN6ZTNEQ1JyTHhRaDQ2
        MTZkdHhEb0lid0tZbm1MeVRqZWpZajgKqPOOkGFaemOq+ul4Vq12h/jQkkRqXWnk
        tQ31XqO+KaIi6hJ6Fkwo/qNFJsiBLvtaCy2OhtzqVzNOH32dvNKXHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aThoeW0vRmRlSHh3cDVu
        bjlPOGdydGlpVnJBUHBwQ2t3WlE1R29zRkhjCjFxemx2Y3ZiSm5idlBUdWxCOVRQ
        dHpVUmlHY1lpc2xkZDdhckpaRFNYb2sKLS0tIFc1M2dZV3FiaW0wNHdPVHVYZVln
        dkJPMXlqdm1kY0ZqMTN2TDNXNTJXcVkKpDgOx0IWi8Q/h8WYwpA82iT38JS9/oyM
        xStyF9trChR4RuvHTcRuedK+tnDJF1GhHqdPNVZ/C2fFxnBDSKJXlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-05-29T20:09:33Z"
  mac: ENC[AES256_GCM,data:vTOAZMSrNAq8mx/SFQFU+rYacL1xUJdvnm2wjAuJF6JV9cXovEU7I0XZamVXcdeh7D+m7dl6G9qVNoXK5iwpof0mNQiTMLJS3G7O1Q2/EJdV0/cJZu6B8zvPSin13KdzRs2PoTfhpySZkJXVJ34ojeTrTRQHx9EivENRqgv5KAk=,iv:i9b3I1Rq1yokb8Az2rx7nXp5oaBKIlY/KVfqyn70B8k=,tag:oXr7/a3yC97Tg5+OOhITRA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
