app-template:
  controllers:
    agent:
      containers:
        app:
          env:
            NB_SETUP_KEY: ENC[AES256_GCM,data:4Ph4+m3AHMGtAWf1fQ9OqABfyp2MsJy4Lxgm,iv:Fyl1go8/dpAV9wotIapLoCqSJ+81yGfQBa8zQCgGCB4=,tag:aNUQtwk0ryg7YKCCiTF75Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT05LWWwreXJPeDJPRmd1
        VDRPQWd1YVo0YjRWaWVpb0ttMXduNUFia1FFCjFydVlLQU5RK0kvTXlUNWl4TlM0
        eG1IWHA1RGpvK2l3WlVaVVhLdkNhRUUKLS0tIFVPTlR4cHN6ZTNEQ1JyTHhRaDQ2
        MTZkdHhEb0lid0tZbm1MeVRqZWpZajgKqPOOkGFaemOq+ul4Vq12h/jQkkRqXWnk
        tQ31XqO+KaIi6hJ6Fkwo/qNFJsiBLvtaCy2OhtzqVzNOH32dvNKXHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aThoeW0vRmRlSHh3cDVu
        bjlPOGdydGlpVnJBUHBwQ2t3WlE1R29zRkhjCjFxemx2Y3ZiSm5idlBUdWxCOVRQ
        dHpVUmlHY1lpc2xkZDdhckpaRFNYb2sKLS0tIFc1M2dZV3FiaW0wNHdPVHVYZVln
        dkJPMXlqdm1kY0ZqMTN2TDNXNTJXcVkKpDgOx0IWi8Q/h8WYwpA82iT38JS9/oyM
        xStyF9trChR4RuvHTcRuedK+tnDJF1GhHqdPNVZ/C2fFxnBDSKJXlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-05-29T20:23:37Z"
  mac: ENC[AES256_GCM,data:7bXDfU4E2s4ao1wxV/gElwJJCJXCW/50Ta+f/7TYN5ba2Yrz7FvUM+QfFn9fNkhIeRlb9rj6wyAsRAP3AzuIGWyMvlj8wVrykpIoXceX53OdHajFJFe1oFtcZfPumPRmdt7IcChCFbqjFm6+95DwVlW5PRT/l57Dj4QZcOBDnqs=,iv:HAIXXQsCssD9O3sBq33gPtKaooliH/Azql9Ea7DXtgM=,tag:asUvfHq5a0EaP/PeuXewOg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
