app-template:
  controllers:
    agent:
      containers:
        app:
          env:
            NB_SETUP_KEY: ENC[AES256_GCM,data:ATpsLxpBjM4XdwPQxNjQ5C61T+DnH3BLIpWIn3Faib4YpW5K,iv:Fl+xBf6wp+w13MDfvZHc+FsKf2uzvTwCg+jo4kAMKVM=,tag:NX+t50guxmSUoS3a5djbGQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT05LWWwreXJPeDJPRmd1
        VDRPQWd1YVo0YjRWaWVpb0ttMXduNUFia1FFCjFydVlLQU5RK0kvTXlUNWl4TlM0
        eG1IWHA1RGpvK2l3WlVaVVhLdkNhRUUKLS0tIFVPTlR4cHN6ZTNEQ1JyTHhRaDQ2
        MTZkdHhEb0lid0tZbm1MeVRqZWpZajgKqPOOkGFaemOq+ul4Vq12h/jQkkRqXWnk
        tQ31XqO+KaIi6hJ6Fkwo/qNFJsiBLvtaCy2OhtzqVzNOH32dvNKXHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aThoeW0vRmRlSHh3cDVu
        bjlPOGdydGlpVnJBUHBwQ2t3WlE1R29zRkhjCjFxemx2Y3ZiSm5idlBUdWxCOVRQ
        dHpVUmlHY1lpc2xkZDdhckpaRFNYb2sKLS0tIFc1M2dZV3FiaW0wNHdPVHVYZVln
        dkJPMXlqdm1kY0ZqMTN2TDNXNTJXcVkKpDgOx0IWi8Q/h8WYwpA82iT38JS9/oyM
        xStyF9trChR4RuvHTcRuedK+tnDJF1GhHqdPNVZ/C2fFxnBDSKJXlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-06-04T16:34:40Z"
  mac: ENC[AES256_GCM,data:f1ZwyMUHVNtAbcg1bOYw/Rx8L5wvqdEhZqilmN+2osMH/YH51C7VmtnLomqlFSkICsaFJ6S8/aQnf2JDhayZqcG4KRan2MpIB1EcXadTYC2N82cQwqIAiDfaAXqSzF4ljeB/nfzo6lvGUPO+gXhO3tOdnqp19MC2i1iSEHEcazU=,iv:Y2h4oGswPzW6LSxfLA6+r2EziGC2ho3VdaIX/POROv4=,tag:I/7X6XGwe0FRt4VR3K2NwA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
