app-template:
  controllers:
    cod2-statistics:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        app:
          image:
            repository: ghcr.io/blarc/cod2-statistics
            tag: latest
            pullPolicy: Always
          env:
            TZ: Europe/Ljubljana
            LOKI_URL: http://loki.observability:3100
            LOKI_QUERY: '{service_name="cod2"}'
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /health
                  port: &port 8080
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: [ "ALL" ] }
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
  service:
    app:
      ports:
        http:
          port: *port
  route:
    app:
      hostnames:
        - "{{ .Release.Name }}.blarc.my.id"
      parentRefs:
        - name: external
          namespace: traefik
      rules:
        - backendRefs:
            - identifier: app
              port: *port
          matches:
            - path:
                type: PathPrefix
                value: /
  networkpolicies:
    app:
      controller: cod2-statistics
      policyTypes:
        - Ingress
        - Egress
      rules:
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: traefik
            ports:
              - protocol: TCP
                port: *port
        egress:
          - to:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: observability
                podSelector:
                  matchLabels:
                    app.kubernetes.io/name: loki
            ports:
              - protocol: TCP
                port: 3100
          - to:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: kube-system
            ports:
              - protocol: UDP
                port: 53
              - protocol: TCP
                port: 53
  persistence:
    data:
      type: persistentVolumeClaim
      storageClass: topolvm-thin
      accessMode: ReadWriteOnce
      size: 1Gi
