sftpgo:
  config:
    httpd:
      bindings:
        - oidc:
            client_id: ENC[AES256_GCM,data:m4dYA7fOaMhINuOdsPMkBnd/pMSE/0DhDMWC3NQjXtxgky/LaVTkxA==,iv:5OnYmz0++nd6sHPeJok8IY79uOTJswARDHLAguLGBVU=,tag:KlOzogEqf6sQ4BQKrdhfuQ==,type:str]
            client_secret: ENC[AES256_GCM,data:bbGFGalNcAs3yt0GNn5iZfBr4bdsfrrQb40FbSR+EeNv1p7xY9sVMu9wGe4zOzfWd1MipboTQB7P/VnMCubB7Q/UmYjXqQcSksGJpe7F7swpZyouF9JvaSY3pqeILvbiOKWuLu0LKCkuLuoWMOqEo570Q04/icJslA30zEkeGyc=,iv:traoHuFWI6yBuS8G1hl1qP/q6jcf5lSDju4AFhpF0+o=,tag:3uslS5R89IXJy6lRrlE5ug==,type:str]
            config_url: ENC[AES256_GCM,data:rSdDhvLcHtMUDTzqpnVANWESWSg2AVHO,iv:nFVIx3nR9fEUe9MHxUyrmEhL736OUhq/yjnGeegp21M=,tag:bCR8XkbOsbiJB4vHKZQYqA==,type:str]
            redirect_base_url: ENC[AES256_GCM,data:WteZHYB9OiPpITdRNskTHJczOObmhNp41PQ=,iv:hyMHSvwhPmydwN4J2oa+CgxsYOvOJXA+lYMUgbSkO3I=,tag:cKkMr+XqiWbNtL+MCUz+jg==,type:str]
            username_field: ENC[AES256_GCM,data:laUzlN6uRm5RNmUaRmC8QcVl,iv:KM3LyVsKXBbAJ3HbA8ihf64ucX+rg0p9O9SNP6QpjSU=,tag:dHX1FPYHYeoYhftiuCM0jw==,type:str]
            display_name: ENC[AES256_GCM,data:QxATue4/j24=,iv:RJkZ1md/d/w1hhIChCc7qwANplMqaI5T+4We9rWzqcQ=,tag:tVZp+9mVlx5q8b0FvRCsrA==,type:str]
            role_field: ENC[AES256_GCM,data:ko+mSNCVVO2FI1w=,iv:+XSDMdrMY+M4lWNraJJiEIkdgLCcI0tmgMJu+ty/sl4=,tag:LeGydRJGyvF9t+4D7AHPkA==,type:str]
            implicit_roles: ENC[AES256_GCM,data:SpQkXMw=,iv:9jrf4+AyZkgcbaQyPwwOtNDxMBCx2cSZ6wFJcuau2uk=,tag:kZlr8xxRAdv5WPClw+HEdg==,type:bool]
            custom_fields: []
            scopes:
              - ENC[AES256_GCM,data:q3j6eypI,iv:t7I5ddTkSADQ7KYSbR5przJt+AQ2/4whcy6nKcxY6MA=,tag:YN6Zv8Qz4BWT6Lbewyo5JA==,type:str]
              - ENC[AES256_GCM,data:nCY8W2mvvA==,iv:RDdWzctRAzrs1OCMyjJx4rnNZGs5p+Z1tB6dunLdRc0=,tag:ezumbMQpkCrGQ/yrNKhdXA==,type:str]
              - ENC[AES256_GCM,data:AgB1t5Q=,iv:cJjlnhckAfLBvaKZWP0Gv0p1E2yGNSYA7BiXRFDy79w=,tag:MDw8DjtvJSep8/CO50KACw==,type:str]
              - ENC[AES256_GCM,data:t7drpwBmCmCb2ATuDFM=,iv:4YxC7dWq32no9FW824HweJzku39ijKL7h68Dhee3g5M=,tag:Sh3GcyJQaFWQKqll7g1maA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Szlpb1FIYi84MHB5VW4z
        VWZVTWxuVk1GeTI1NWJGak96ZUpQUmVFZURvCnV4ZzdpVWNDczJyZVJ3MnVKSlhE
        TGhFZlpkWFpYQVl0OVp4QS8yWUNPREkKLS0tIGdVNStCSmZWZjVQSHFhdFloYUJX
        d0dzUEtFZ2c5NUJuSUsyVVkrcHR2U28KR1R/7XldOyh4uKDxDbpgHoFoV0FMCXMU
        DI7FplgiiRmcGja2y7E4yb/APbP08i4sKFhDXPs52ZAdHlLtqR96Ug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTlp0THBMVVdjTGQzV0dX
        c0MyaFROdGhWRXlGSEZPaStDMjhyTFo5WW5NCnpYend2dnVwTnN0YnEyelc3TThG
        dDJxWVNpNVB1eDZKdVFiZjNpQ09BWnMKLS0tICtxQUlVSFNTR3F0Sms2eXlpNm9s
        NjRnWDh6dEZYM0ZIL2loR1p4eFozbGsKYGbwGG7FDfBj06gttp1jtO0LO5+tMeEN
        lyR6U3mf68o4cXvfX+eUZ9YLwEPaWHWiBqrXY772+uA1yjNMDRiM+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-07-26T10:10:48Z"
  mac: ENC[AES256_GCM,data:0cKP+8r6R90r2vr8XEHKmBgRM+xpbITFRBn48X+vIy6OdQCDvEDYjmVFgP6jcxa29YZP7TaCCNYG2vIJ29A9uMs/XdTaR9eD8Wm3VDY/mTEZf71YY0A3G2EBcbrj21/vlfZaLvj4IRYPh/rDHXGZSDnDQQSauTbulpNztZJY1fY=,iv:/ccFrwYrSlEJYDIYdrkiTHjR6TPlfz5TVfe9Uzivw88=,tag:Qtc0NLas+h+03KHc8CezRA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.2
