sftpgo:
  config:
    httpd:
      bindings:
        - oidc:
            client_id: ENC[AES256_GCM,data:x6JlcNspajLb+jdzKn7JBSp0q6lhLkjlB3HINto5fz5HmjcMoK9v1A==,iv:2i4AQDp5kXz0vFLOevXaz9M7hxAKfnzMaLQQUUKwCgk=,tag:oog7w4EttcQizCadOvtgUg==,type:str]
            client_secret: ENC[AES256_GCM,data:QSJj9ccAy4H4+kbAB30l+gL/OWvFH4zs9ZaDrD8eRMkd/FTTsvXVFmkhcB+bcHCSRoL568h+wEY2J95Y8r2U9qX8Qtw2wbO5OTnOzQX9VwvUT+U7YLmjnJcIfycWVdcEU7ep231Nv7yRMxnDolnBOvRdZf50KBEKM6rxQrZ5enE=,iv:Ab07nqR5nyFt7+4bmTmK8R15dif4q7Ys6CAdG6ldTzQ=,tag:LA73ZZtHjhoSz0BXBcB5dg==,type:str]
            config_url: ENC[AES256_GCM,data:sr6Na9ofIUL8b0i66qjDKFZDj+Pg0G9qHd9sJ78eKoLbpXGkDGr9CqqT3vgn1clGOwy0,iv:rKhllcTw4A0plQutv8GiiQioPNzbrNJ+jvkHAhallXk=,tag:vSexogqT6wBfk4CnMVWMMA==,type:str]
            redirect_base_url: ENC[AES256_GCM,data:bsne0T+TQKcNcB00fjy56EtonG1dYsbjwIA=,iv:cqJmDatBbASFnYJaBHjZWenignAo/NPQ1rJI4ONFsd8=,tag:ooXCUjp/nXpIc/BUMZ12lQ==,type:str]
            username_field: ENC[AES256_GCM,data:cSqTpsPQK4B1FetsB07UMuqP,iv:QilJBzEQTOhA4hQ3bcPDjmsdlNZseqFZ06wIVPBfFnY=,tag:RSYbqTIyXHSGWoy66Fds4g==,type:str]
            display_name: ENC[AES256_GCM,data:nPmNKdd1PlxI,iv:mAi3oX2/emF24kkpk3OiD1ZsniYAg1A6/WSAep2Aams=,tag:4zNhUUYA2pJhr5US38cybw==,type:str]
            role_field: ENC[AES256_GCM,data:kAIP3Rud8Kef8O8=,iv:jn7RafaycLGcc6mUr3rLogyuo9k54IhyMX5pbneTgIQ=,tag:FnYprhollDPTILakYdwu+g==,type:str]
            implicit_roles: ENC[AES256_GCM,data:3AEhFVo=,iv:SaVys1+w5aCt/xBtAIzHRGl8L80wzyGsBGtzhyPh5Bc=,tag:cYEwKTjhIrZ+ARakGc/8Fg==,type:bool]
            custom_fields: []
            scopes:
              - ENC[AES256_GCM,data:6hThoKKl,iv:7YW6T2AGDyVlgSvdnkw7f605vpvwcfu+REjARRowNbw=,tag:j2yBcYt6dKD/JvbawjhKPA==,type:str]
              - ENC[AES256_GCM,data:t4847dGObg==,iv:+SobWCVaE3V7CKdizrGqL8GEPkujD7FvJ3wWoGY/xeo=,tag:0pyELK7UT7Tz919PgIRmpQ==,type:str]
              - ENC[AES256_GCM,data:SGPQTPk=,iv:QoYTqY5QGu7cmkxIE1OhXUfB66YCGJNPoceXH8v+oAE=,tag:PFMwaxc0y99nAAHPY2Jd7Q==,type:str]
              - ENC[AES256_GCM,data:IqgMuoIsnQGlkYcZWkE=,iv:I0qhZS+fQrjFZzYYGrg/wBfhqcwtEv9Z8E1BC8F3ZUU=,tag:wV2KuX3Wfu4u7Fr9UmQUcg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWk40enNEeGFQYVNxOERt
        Z0VPZHcxYnFtK1VsajJyVFhBQVg2MlZhaVd3CjNDL0UyMWRaMjZ2dzc5T3hMQitM
        dDFKRktJaWswdjR0TUlpNTU1a0hLUVUKLS0tIDJFK2x1RHkvSFJURE55dElvNmsw
        bCsrV3RjU3hCSE5FQkkwQk5sVmtJRVEK4fvQj0TJozLEWg4i6+OFCK6QAs/TvKAZ
        mD53mOg+tNLMiYruj6vx1rZQTcljeSHRqoZs05i8xYLZCxVbMopVwQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQzlzcndCTTB6WHczdXYw
        ZTE4VTRIeVEzK2lKRE1zcDd6VDBDMzMvZm5VCmp2byttL2tFeUVkNGhSVGs3TUFo
        TmVNTkQzQkRMbU8yR1ZpRSt4OWdYUFkKLS0tIE5FVGhZSVRZRmtxSi9HSnNSU2d4
        WEFlakVpNk9NeEJwOHpiNEQxa1pibzQKo800/R/x984oPgFAJtK7WGdBfDo6rNN0
        2H2SxTpM40LBsovjMmfYzgoCoz8ScVJmO97taZEtwikXssWepkzJnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
  lastmodified: "2026-06-05T18:42:43Z"
  mac: ENC[AES256_GCM,data:xnfh7kYF8XoauoyaIUJTs0LYrF5BdWqDA4jCLSGzsRZ3JP+9UCiFHAtopgbqt/yLfjAac9X3ZnetLbBEXw0vvbhRkaYb7NVdrgQRheZPOxkuLZDsOLYUqAVL5egTV5mu0myB/34pJ5MdQ+MK+7s+ywFfYFX3vxmaMpsCNMtQ938=,iv:KeNGW3fPR16J91iShCVyvCjfzNL/eZukll9OBz5kZow=,tag:65t7E98EyMMKxRh3yXdbow==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
