sftpgo:
  revisionHistoryLimit: 3

  gatewayApi:
    httpRoutes:
      ui:
        enabled: true
        hostnames:
          - sftpgo.blarc.my.id
        parentRefs:
          - name: internal
            namespace: traefik
      api:
        enabled: true
        hostnames:
          - sftpgo.blarc.my.id
        parentRefs:
          - name: internal
            namespace: traefik

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
     memory: 1Gi

  config:
    data_provider:
      users_base_dir: /srv/sftpgo/data
    httpd:
      bindings:
        oidc:
          config_url: https://authentik.blarc.my.id/application/o/sftpgo
          redirect_base_url: https://sftpgo.blarc.my.id
          username_field: "preferred_username"
          role_field: "sftpgo_role"
          implicit_roles: false
          custom_fields: []

  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data

  volumeMounts:
    - name: data
      mountPath: /srv/sftpgo/data

  persistence:
    # -- Enable persistent storage for the /var/lib/sftpgo directory, saving state of the default sqlite db.
    enabled: true
    pvc:
      resources:
        requests:
          storage: 1Gi
      storageClassName: "topolvm-thin"