app-template:
  controllers:
    jellyfin:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        app:
          image:
            repository: ghcr.io/jellyfin/jellyfin
            tag: 10.11.11
          env:
            JELLYFIN_PublishedServerUrl: "https://{{ .Release.Name }}.blarc.my.id"
            TZ: Europe/Ljubljana
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /health
                  port: &containerPort 8096
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 5
            readiness: *probes
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: [ "ALL" ] }
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 2Gi
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
  service:
    app:
      ports:
        http:
          port: &port 80
          targetPort: *containerPort
  route:
    app:
      hostnames:
        - "{{ .Release.Name }}.blarc.my.id"
      parentRefs:
        - name: internal
          namespace: traefik
      rules:
        - backendRefs:
            - identifier: app
              port: *port
          matches:
            - path:
                type: PathPrefix
                value: /
  persistence:
    config:
      type: persistentVolumeClaim
      storageClass: topolvm-thin
      accessMode: ReadWriteOnce
      size: 3Gi
    cache:
      type: persistentVolumeClaim
      storageClass: topolvm-thin
      accessMode: ReadWriteOnce
      size: 3Gi
    media:
      existingClaim: qbittorrent-media
      globalMounts:
        - path: /media
          readOnly: true
    tmp:
      type: emptyDir
