# $schema: https://helm-values-schemas.onrender.com/grafana/loki/refs/heads/main/production/helm/loki/values.yaml
deploymentMode: SingleBinary
loki:
  # Remove this when persistence is set up.
  useTestSchema: true
  auth_enabled: false
  analytics:
    reporting_enabled: false
  server:
    log_level: info
  commonConfig:
    replication_factor: 1
  #      compactor:
  #        working_directory: /var/loki/compactor/retention
  #        delete_request_store: filesystem
  #        retention_enabled: true
  ingester:
    chunk_encoding: snappy
  storage:
    type: none
  schemaConfig: { }
  limits_config:
    retention_period: 1h
singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumes:
    - name: var-loki
      emptyDir: { }
  extraVolumeMounts:
    - mountPath: /var/loki
      name: var-loki
#        storageClass: ceph-block
#        size: 50Gi
gateway:
  replicas: 0
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
compactor:
  replicas: 0
ruler:
  enabled: false
chunksCache:
  enabled: false
resultsCache:
  enabled: false
lokiCanary:
  enabled: false
test:
  enabled: false
sidecar:
  image:
    repository: ghcr.io/kiwigrid/k8s-sidecar
  rules:
    searchNamespace: ALL
