apiVersion: v2
dependencies:
  - name: openclaw-operator
    repository: oci://ghcr.io/openclaw-rocks/charts
    version: 0.24.1
description: Helm chart to deploy openclaw-operator
name: openclaw-operator
version: 1.0.0
