apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    # Protects when moving/deleting files in Git
argocd.argoproj.io/sync-options: Prune=false
# Protects when deleting the parent Applicationargocd.argoproj.io/sync-options: Delete=false
  labels:
    external: "true"
