argo-cd:
  fullnameOverride: argo-cd
  namespaceOverride: argo-cd
  crds:
    install: false
  createClusterRoles: true
  global:
    domain: argo-cd.blarc.my.id
  server:
    resources:
      requests:
        cpu: 25m
        memory: 96Mi
      limits:
        memory: 256Mi
    httproute:
      enabled: true
      hostnames:
        - argo-cd.blarc.my.id
      parentRefs:
        - name: internal
          namespace: traefik
  controller:
    replicas: 1
    resources:
      requests:
        cpu: 150m
        memory: 512Mi
      limits:
        memory: 1Gi
    roleRules:
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs:
          - '*'

  dex:
    enabled: false

  repoServer:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 512Mi
    image:
      repository: ghcr.io/blarc/home-k8s/argo-cd
      tag: v3.5.2-c8522240
      imagePullPolicy: Always
    imagePullSecrets:
      - name: argocd-gitlab-registry-secret
    env:
      - name: SOPS_AGE_KEY_FILE
        value: /argocd-helm-secrets-private-keys/key.txt
    volumes:
      - name: argocd-helm-secrets-private-keys
        secret:
          secretName: argocd-helm-secrets-private-keys
    volumeMounts:
      - mountPath: /argocd-helm-secrets-private-keys/
        name: argocd-helm-secrets-private-keys
  applicationSet:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 256Mi
  notifications:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi
  redis:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi
  redisSecretInit:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi
  configs:
    params:
      server.insecure: true
    cm:
      admin.enabled: true
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#auto-respect-rbac-for-controller
      resource.respectRBAC: "normal"
      application.resourceTrackingMethod: annotation+label
      helm.valuesFileSchemes: >-
        secrets+gpg-import, secrets+gpg-import-kubernetes,
        secrets+age-import, secrets+age-import-kubernetes,
        secrets, secrets+literal,
        https

argocd-image-updater:
  fullnameOverride: argo-cd-image-updater
  crds:
    keep: false
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
