kind: Secret
apiVersion: v1
metadata:
  name: spaceship-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  api-key: "{{ .Values.secret.apiKey }}"
  api-secret: "{{ .Values.secret.apiSecret }}"