# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  force: true
  interval: 30m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: podinfo
  targetNamespace: default
  timeout: 3m0s
  wait: true
  patches:
    - target:
        kind: Deployment
        name: podinfo
      patch: |
        - op: replace
          path: /spec/replicas
          value: 1
    - target:
        kind: HorizontalPodAutoscaler
        name: podinfo
      patch: |
        - op: replace
          path: /spec/minReplicas
          value: 1
        - op: replace
          path: /spec/maxReplicas
          value: 3
    - target:
        kind: Service
        name: podinfo
      patch: |
        - op: replace
          path: /spec/type
          value: LoadBalancer
