apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: podinfo
  namespace: default
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - "podinfo.blarc.my.id"
  rules:
    - backendRefs:
      - name: podinfo
        port: 9898
