apiVersion: v2
dependencies:
  - name: victoria-metrics-k8s-stack
    repository: oci://ghcr.io/victoriametrics/helm-charts
    version: 0.91.2
description: Helm chart to deploy victoria-metrics-k8s-stack
name: victoria-metrics-k8s-stack
version: 1.0.0
