apiVersion: v1
kind: Secret
metadata:
  name: alertmanager
  namespace: observability
type: Opaque
stringData:
  alertmanager.yaml: |
    route:
      receiver: ntfy
      repeat_interval: 12h
      group_by:
        - alertname
        - cluster
        - job
      group_interval: 5m
      group_wait: 1m
      routes:
        - receiver: blackhole
          matchers:
            - alertname="InfoInhibitor"
        - receiver: ntfy
    inhibit_rules:
      - equal:
          - alertname
          - namespace
        source_matchers:
          - severity="critical"
        target_matchers:
          - severity="warning"
    receivers:
      - name: blackhole
      - name: ntfy
        webhook_configs:
          - url: "{{ .Values.alertmanager.ntfyUrl }}"
            http_config:
              basic_auth:
                username: "{{ .Values.alertmanager.ntfyUsername }}"
                password: "{{ .Values.alertmanager.ntfyPassword }}"
